<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>11&nbsp; Diagnósticos parte II – Análisis de regresión con R</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./12-ph-homoce.html" rel="next">
<link href="./10-diag1.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-0d3ac16015dd0859924b68075192f47b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./11-diag2.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Diagnósticos parte II</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Análisis de regresión con R</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefacio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-rls.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Regresión lineal simple</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-transf.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Transformaciones</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-rlm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Regresión lineal múltiple</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-predict.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Predicción</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-simul.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Simulación</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-ic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Intervalos de confianza</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-var_cuali.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Modelos con variables cualitativas</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-ph1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Pruebas de hipótesis parte I</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-ph2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Pruebas de hipótesis parte II</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-diag1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Diagnósticos parte I</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-diag2.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Diagnósticos parte II</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-ph-homoce.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Pruebas de Homocedasticidad</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-ph-indep.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Pruebas de independencia de los errores</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-mod_poli.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Modelos polinomiales</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-all_possible_reg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Todas las regresiones posibles</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-selecvar.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Selección de variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-feature_selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Feature selection</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-multicoli.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Multicolinealidad</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-coefEstandarizados.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Regresión con coeficientes de regresión estandarizados</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-algebramatricial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Algebra matricial con R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21-Wilkinson-Rogers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Notación de Wilkinson y Rogers</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./22-xy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">¿Cómo obtener la matriz <span class="math inline">\(\boldsymbol{X}\)</span> y el vector <span class="math inline">\(\boldsymbol{y}\)</span>?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./23-behind.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Otros aspectos importantes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./24-pasos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Pasos para construir modelos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./25-misspecification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Mala especificación</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#matriz-sombrero-o-hat" id="toc-matriz-sombrero-o-hat" class="nav-link active" data-scroll-target="#matriz-sombrero-o-hat">Matriz sombrero o hat</a></li>
  <li><a href="#qué-es-extrapolación-oculta" id="toc-qué-es-extrapolación-oculta" class="nav-link" data-scroll-target="#qué-es-extrapolación-oculta">¿Qué es extrapolación oculta?</a>
  <ul class="collapse">
  <li><a href="#ejemplo" id="toc-ejemplo" class="nav-link" data-scroll-target="#ejemplo">Ejemplo</a></li>
  <li><a href="#reto-para-el-lector" id="toc-reto-para-el-lector" class="nav-link" data-scroll-target="#reto-para-el-lector">Reto para el lector</a></li>
  </ul></li>
  <li><a href="#punto-de-balanceo" id="toc-punto-de-balanceo" class="nav-link" data-scroll-target="#punto-de-balanceo">Punto de balanceo</a></li>
  <li><a href="#punto-atípico-outlier-y-punto-influyente" id="toc-punto-atípico-outlier-y-punto-influyente" class="nav-link" data-scroll-target="#punto-atípico-outlier-y-punto-influyente">Punto atípico (outlier) y punto influyente</a></li>
  <li><a href="#uso-de-los-residuales-para-detectar-atípicos-outliers" id="toc-uso-de-los-residuales-para-detectar-atípicos-outliers" class="nav-link" data-scroll-target="#uso-de-los-residuales-para-detectar-atípicos-outliers">Uso de los residuales para detectar atípicos (outliers)</a></li>
  <li><a href="#prueba-de-bonferroni-para-detectar-atípicos-outliers" id="toc-prueba-de-bonferroni-para-detectar-atípicos-outliers" class="nav-link" data-scroll-target="#prueba-de-bonferroni-para-detectar-atípicos-outliers">Prueba de Bonferroni para detectar atípicos (outliers)</a>
  <ul class="collapse">
  <li><a href="#ejemplo-1" id="toc-ejemplo-1" class="nav-link" data-scroll-target="#ejemplo-1">Ejemplo</a></li>
  </ul></li>
  <li><a href="#distancia-de-cook" id="toc-distancia-de-cook" class="nav-link" data-scroll-target="#distancia-de-cook">Distancia de Cook</a>
  <ul class="collapse">
  <li><a href="#ejemplo-2" id="toc-ejemplo-2" class="nav-link" data-scroll-target="#ejemplo-2">Ejemplo:</a></li>
  </ul></li>
  <li><a href="#dffits" id="toc-dffits" class="nav-link" data-scroll-target="#dffits">DFFITS</a></li>
  <li><a href="#dfbetas" id="toc-dfbetas" class="nav-link" data-scroll-target="#dfbetas">DFBETAS</a>
  <ul class="collapse">
  <li><a href="#ejemplo-3" id="toc-ejemplo-3" class="nav-link" data-scroll-target="#ejemplo-3">Ejemplo</a></li>
  </ul></li>
  <li><a href="#estadística-press-y-r2-de-predicción" id="toc-estadística-press-y-r2-de-predicción" class="nav-link" data-scroll-target="#estadística-press-y-r2-de-predicción">Estadística PRESS y <span class="math inline">\(R^2\)</span> de predicción</a>
  <ul class="collapse">
  <li><a href="#ejemplo-4" id="toc-ejemplo-4" class="nav-link" data-scroll-target="#ejemplo-4">Ejemplo</a></li>
  </ul></li>
  <li><a href="#valores-de-corte-para-diagnósticos" id="toc-valores-de-corte-para-diagnósticos" class="nav-link" data-scroll-target="#valores-de-corte-para-diagnósticos">Valores de corte para diagnósticos</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="diag2" class="quarto-section-identifier"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Diagnósticos parte II</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>En este capítulo se presentan otras herramientas útiles para realizar diagnósticos.</p>
<section id="matriz-sombrero-o-hat" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="matriz-sombrero-o-hat">Matriz sombrero o hat</h2>
<p>La matriz sombrero o matriz Hat se define así:</p>
<p><span class="math display">\[
\boldsymbol{H} = \boldsymbol{X}(\boldsymbol{X}^\top \boldsymbol{X})^{-1}\boldsymbol{X}^\top
\]</span></p>
<p>Esta matriz contiene en su diagonal las distancias relativas desde el centroide de los datos hasta cada uno de los puntos. En la siguiente figura se ilustra el concepto de distancia relativa entre el centroide (color rojo) de las variables explicativas y cada uno de los puntos para un caso con tres variables explicativas <span class="math inline">\(x_1\)</span>, <span class="math inline">\(x_2\)</span> y <span class="math inline">\(x_3\)</span>.</p>
<p align="center">
<img src="images/ilustracion_hat.png" width="300">
</p>
<p>La cantidad <span class="math inline">\(h_{ii}\)</span> se llama leverage y corresponde al elemento <span class="math inline">\(i\)</span> de la diagonal de la matriz sombrero <span class="math inline">\(\boldsymbol{H}\)</span>. Los valores de <span class="math inline">\(h_{ii}\)</span> cumplen lo siguiente:</p>
<ul>
<li>siempre están entre <span class="math inline">\(1/n\)</span> y 1.</li>
<li>la suma <span class="math inline">\(\sum h_{ii}\)</span> es igual al número de <span class="math inline">\(\beta\)</span>’s del modelo (incluyendo <span class="math inline">\(\beta_0\)</span>).</li>
</ul>
<p>Si la observación <span class="math inline">\(i\)</span>-ésima tiene un valor grande de <span class="math inline">\(h_{ii}\)</span> significa que ella tiene valores inusuales de <span class="math inline">\(\boldsymbol{x}_i\)</span>, mientras que valores pequeños de <span class="math inline">\(h_{ii}\)</span> significa que la observación se encuentra cerca del centroide de los datos.</p>
<div class="cell" type="rmdwarning">

<div class="rmdwarning">
La distancia <span class="math inline">\(h_{ii}\)</span> no incluye información de la variable respuesta <span class="math inline">\(y\)</span>, solo de las covariables, esto se nota claramente en la fórmula de <span class="math inline">\(\boldsymbol{H}\)</span> dada arriba.
</div>
</div>
<p>Los valores <span class="math inline">\(h_{ii}\)</span> se pueden obtener de dos formas:</p>
<ul>
<li>Construyendo la matriz <span class="math inline">\(\boldsymbol{H}\)</span>.</li>
<li>Ajustando el modelo de regresión <code>mod</code> y luego usando la función <code>hatvalues(mod)</code> o <code>lm.influence(mod)</code> sobre el modelo.</li>
</ul>
<p>¿Para qué se usan los <span class="math inline">\(h_{ii}\)</span> en la práctica?</p>
<p>En el siguiente apartado se explicará el uso de los <span class="math inline">\(h_{ii}\)</span>.</p>
</section>
<section id="qué-es-extrapolación-oculta" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="qué-es-extrapolación-oculta">¿Qué es extrapolación oculta?</h2>
<p>Suponga tenemos un modelo de regresión una variable respuesta y dos covariables <span class="math inline">\(x_1\)</span> y <span class="math inline">\(x_2\)</span>. En la siguiente figura se ilustra los posibles datos desde una vista superior (sin ver los valores de <span class="math inline">\(y\)</span>). Esa elipse o forma se llama Regressor Variable Hull (RVH) o cascarón de los datos.</p>
<p align="center">
<img src="images/extrapolacion_oculta.png" width="500">
</p>
<p>Una vez se tenga el modelo ajustado podríamos usar valores de <span class="math inline">\(x_1\)</span> y <span class="math inline">\(x_2\)</span> para estimar la media de <span class="math inline">\(y\)</span>. Lo ideal es usar el modelo para predecir la media de <span class="math inline">\(y\)</span> con valores de <span class="math inline">\(x_1\)</span> y <span class="math inline">\(x_2\)</span> que se encuentren dentro del cascarón.</p>
<p>Si tratamos de estimar la media de <span class="math inline">\(y\)</span> para valores de las covariables fuera del cascarón, como en el caso del punto rojo, no podemos garantizar que el modelo tenga un buen desempeño debido a que el modelo no se entrenó con ese tipo de ejemplos.</p>
<p>El problema de <strong>extrapolación oculta</strong> se presenta cuando tratamos de predecir información de <span class="math inline">\(y\)</span> con covariables fuera del cascarón. La extrapolación oculta es fácil de identificarla cuando sólo se tiene dos covariables, pero, ¿cómo saber si se está haciendo extrapolación oculta cuando se tienen varias covariables. Supongamos que queremos saber si el vector de covariables <span class="math inline">\(\boldsymbol{x}_0=(1, x_1, x_2, \ldots, x_p)^\top\)</span> está o no dentro del cascarón, dicho de otra manera, ¿se cometería extrapolación oculta usando <span class="math inline">\(\boldsymbol{x}_0\)</span>?. Los pasos para determinar si <span class="math inline">\(\boldsymbol{x}_0\)</span> está o no dentro del cascarón son:</p>
<ol type="1">
<li>Calcular la matriz <span class="math inline">\(\boldsymbol{H}\)</span>.</li>
<li>Obtener los valores <span class="math inline">\(h_{ii}\)</span> de la matriz <span class="math inline">\(\boldsymbol{H}\)</span>.</li>
<li>Identificar <span class="math inline">\(h_{max} = max\{h_{11}, h_{22}, \ldots, h_{nn}\}\)</span>.</li>
<li>Calcular <span class="math inline">\(h_{00} = \boldsymbol{x}_0 (\boldsymbol{X}^\top \boldsymbol{X})^{-1} \boldsymbol{x}_0^\top\)</span>.</li>
<li>Si <span class="math inline">\(h_{00} &gt; h_{max}\)</span> el punto <span class="math inline">\(\boldsymbol{x}_0\)</span> está fuera del cascarón y se podría estár cometiendo extrapolación oculta.</li>
</ol>
<section id="ejemplo" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="ejemplo">Ejemplo</h3>
<p>Calcular los valores <span class="math inline">\(h_{ii}\)</span> para un modelo de regresión <code>y ~ x + z</code> con los siguientes datos.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">6</span>, <span class="dv">5</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">7</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Solución</strong></p>
<p>A seguir se muestran las tres formas para obtener los valores <span class="math inline">\(h_{ii}\)</span>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Forma 1</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="dv">1</span>, x, z)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>H <span class="ot">&lt;-</span> X <span class="sc">%*%</span> <span class="fu">solve</span>(<span class="fu">t</span>(X) <span class="sc">%*%</span> X) <span class="sc">%*%</span> <span class="fu">t</span>(X)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>H</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>              [,1]          [,2]          [,3]          [,4]
[1,]  8.333333e-01  3.333333e-01 -2.609024e-15 -1.666667e-01
[2,]  3.333333e-01  3.333333e-01 -1.665335e-15  3.333333e-01
[3,] -1.387779e-15 -1.332268e-15  1.000000e+00 -1.054712e-15
[4,] -1.666667e-01  3.333333e-01 -1.054712e-15  8.333333e-01</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">diag</span>(H)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8333333 0.3333333 1.0000000 0.8333333</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Forma 2</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x <span class="sc">+</span> z)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hatvalues</span>(mod)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1         2         3         4 
0.8333333 0.3333333 1.0000000 0.8333333 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Forma 3</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lm.influence</span>(mod)<span class="sc">$</span>hat</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1         2         3         4 
0.8333333 0.3333333 1.0000000 0.8333333 </code></pre>
</div>
</div>
</section>
<section id="reto-para-el-lector" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="reto-para-el-lector">Reto para el lector</h3>
<p>Use la información del ejemplo anterior y determine si la observación con valores de <span class="math inline">\(x=4\)</span> y <span class="math inline">\(z=1\)</span> está o no dentro del cascarón de los datos, en otras palabras, determine si se podría cometer extrapolación oculta al usar el modelo ajustado con <span class="math inline">\(x=4\)</span> y <span class="math inline">\(z=1\)</span>.</p>
</section>
</section>
<section id="punto-de-balanceo" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="punto-de-balanceo">Punto de balanceo</h2>
<p>Un punto de balanceo es una observación en el espacio de las predictoras pero alejada del resto de la muestra y que puede controlar ciertas propiedades del modelo ajustado.</p>
<p>Este tipo de observaciones posiblemente no afecte los coeficientes de regresión estimados pero sí las estadísticas de resumen como el <span class="math inline">\(R^2\)</span> y los errores estándar de los coeficientes estimados.</p>
<p>Los puntos de balanceo son detectados mediante el análisis de los elementos de la diagonal principal de la matriz <span class="math inline">\(\boldsymbol{H}\)</span>, los <span class="math inline">\(h_{ii}\)</span> proporcionan una medida estandarizada de la distancia de la <span class="math inline">\(i\)</span>-ésima observación al centro del espacio definido por las predictoras.</p>
<div class="cell" type="rmdnote">

<div class="rmdnote">
Se asume que la observación <span class="math inline">\(i\)</span> es un <strong>punto de balanceo</strong> si <span class="math inline">\(h_{ii} &gt; 2p/n\)</span>, pero si <span class="math inline">\(2p/n &gt; 1\)</span>, este criterio no funciona pues los <span class="math inline">\(h_{ii}\)</span> siempre son menores que 1.
</div>
</div>
</section>
<section id="punto-atípico-outlier-y-punto-influyente" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="punto-atípico-outlier-y-punto-influyente">Punto atípico (outlier) y punto influyente</h2>
<p>Los conceptos de atípico e influyente son diferentes y se definen así:</p>
<ul>
<li>Punto atípico (outlier): es una observación que es numéricamente distante del resto de los datos.</li>
<li>Punto influyente: es una observación que tiene impacto en las estimativas del modelo.</li>
</ul>
<p>En la siguiente figura se ilustra la diferencia entre los conceptos de atípico e influyente.</p>
<p align="center">
<img src="images/atipico_influyente.png" width="500">
</p>
<p>Dos preguntas que surgen al mirar la figura anterior son:</p>
<ul>
<li>¿Cómo saber si un punto es un atípico (outlier)?</li>
<li>¿Cómo saber si un punto es influyente?</li>
</ul>
<p>Para saber si un punto es atípico (outlier) se puede usar la prueba de Bonferroni o los residuales <span class="math inline">\(d_i\)</span> o <span class="math inline">\(r_i\)</span>, y para saber si un punto es influyente se puede utilizar Distancia de Cook. En las siguientes secciones se mostrará cómo identificar atípicos y puntos influyentes.</p>
</section>
<section id="uso-de-los-residuales-para-detectar-atípicos-outliers" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="uso-de-los-residuales-para-detectar-atípicos-outliers">Uso de los residuales para detectar atípicos (outliers)</h2>
<p>Una forma sencilla de detectar posibles observaciones atípicas (outliers) es usando las siguientes reglas:</p>
<ul>
<li>Un <span class="math inline">\(d_i\)</span> grande, <span class="math inline">\(|di| &gt; 3\)</span>, es indicio de una observación potencialmente atípica.</li>
<li>Un <span class="math inline">\(r_i\)</span> grande, <span class="math inline">\(|ri| &gt; 3\)</span>, es indicio de una observación potencialmente atípica.</li>
</ul>
</section>
<section id="prueba-de-bonferroni-para-detectar-atípicos-outliers" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="prueba-de-bonferroni-para-detectar-atípicos-outliers">Prueba de Bonferroni para detectar atípicos (outliers)</h2>
<p>El paquete <strong>car</strong> de <span class="citation" data-cites="R-car">Fox et al. (<a href="references.html#ref-R-car" role="doc-biblioref">2026</a>)</span> tiene la función <code>outlierTest</code> para realizar una prueba de hipótesis de</p>
<ul>
<li><span class="math inline">\(H_0:\)</span> la observación <span class="math inline">\(i\)</span>-ésima NO es un outlier.</li>
<li><span class="math inline">\(H_1:\)</span> la observación <span class="math inline">\(i\)</span>-ésima SI es un outlier.</li>
</ul>
<p>La estructura de la función <code>outlierTest</code> se muestra a continuación.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">outlierTest</span>(model, <span class="at">cutoff=</span><span class="fl">0.05</span>, <span class="at">n.max=</span><span class="dv">10</span>, <span class="at">order=</span><span class="cn">TRUE</span>, <span class="at">labels=</span><span class="fu">names</span>(rstudent), ...)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>En la sección 11.3.1 del libro <span class="citation" data-cites="fox2015applied">Fox (<a href="references.html#ref-fox2015applied" role="doc-biblioref">2015</a>)</span> están los detalles de la prueba, se invita al lector para que los consulte.</p>
<section id="ejemplo-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="ejemplo-1">Ejemplo</h3>
<p>En este ejemplo se usará una base de datos que contiene medidas corporales para un grupo de estudiantes universitarios que vieron el curso de modelos de regresión en el año 2013. Abajo se muestra una figura ilustrativa de los datos.</p>
<p align="center">
<img src="images/medidas_cuerpo_upb.png" width="700">
</p>
<p>El objetivo es determinar si hay alguna observación que se pueda considerar como outlier cuando se ajusta un modelo de regresión para explicar el peso corporal en función de la estatura, circunferencia del cuello y circunferencia de la muñeca.</p>
<p><strong>Solución</strong></p>
<p>Primero vamos a ajustar el modelo y luego vamos a aplicar la prueba de Bonferroni para detectar outliers.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="st">"https://raw.githubusercontent.com/fhernanb/datos/master/medidas_cuerpo2"</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="at">file=</span>url, <span class="at">sep=</span><span class="st">"</span><span class="sc">\t</span><span class="st">"</span>, <span class="at">header=</span><span class="cn">TRUE</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(Peso <span class="sc">~</span> Estatura <span class="sc">+</span> circun_cuello <span class="sc">+</span> circun_muneca, <span class="at">data=</span>datos)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="fu">outlierTest</span>(mod, <span class="at">cutoff=</span><span class="cn">Inf</span>, <span class="at">n.max=</span><span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    rstudent unadjusted p-value Bonferroni p
11  4.206280         0.00011567     0.006015
52 -2.221747         0.03115300           NA
40  2.146046         0.03706400           NA
28 -2.043770         0.04660300           NA</code></pre>
</div>
</div>
<p>En la salida de arriba vemos las cuatro observaciones (<code>n.max=4</code>) que tienen los mayores valores de residual estudentizado <span class="math inline">\(r_i\)</span>. La observación ubicada en la línea 11 es la única con un valor-P muy pequeño y por lo tanto hay evidencias para considerar esa observación como un posible outlier.</p>
<p>Es posible dibujar los resultados de la prueba para cada observación usando la función <code>influenceIndexPlot</code> del paquete <strong>car</strong>. En la siguiente figura se observa que sólo la observacion 11 es identificada como un posible outlier ya que su valor-P es muy pequeño.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">influenceIndexPlot</span>(mod, <span class="at">vars=</span><span class="st">"Bonf"</span>, <span class="at">las=</span><span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="11-diag2_files/figure-html/bonf_test_01-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="distancia-de-cook" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="distancia-de-cook">Distancia de Cook</h2>
<p>Es una medida de cómo influye la observación <span class="math inline">\(i\)</span>-ésima sobre la estimación de <span class="math inline">\(\boldsymbol{\beta}\)</span> al ser retirada del conjunto de datos. Una distancia de Cook grande significa que una observación tiene un peso grande en la estimación de <span class="math inline">\(\boldsymbol{\beta}\)</span>.</p>
<p><span class="math display">\[
D_i = \frac{\sum_{j=1}^{n} (\hat{y}_j - \hat{y}_{j(i)} )^2 }{p \hat{\sigma^2}},
\]</span></p>
<p>donde la notación <span class="math inline">\((i)\)</span> significa “sin la observación <span class="math inline">\(i\)</span>-ésima”, eso quiere decir que <span class="math inline">\(\hat{y}_{j(i)}\)</span> es la estimación de <span class="math inline">\(j\)</span>-ésima sin haber tenido en cuenta <span class="math inline">\(i\)</span>-ésima observación en el ajuste del modelo. La cantidad <span class="math inline">\(p=k+1\)</span> se refiere a todos los <span class="math inline">\(\beta\)</span>’s en el modelo (<span class="math inline">\(\beta_0, \beta_1, \beta_2, \ldots, \beta_k\)</span>).</p>
<p align="center">
<img src="images/get_out.gif" width="400">
</p>
<p>Una forma sencilla de calcular los valores de la distancia de Cook <span class="math inline">\(D_i\)</span> es por medio de la expresión.</p>
<p><span class="math display">\[
D_i = \frac{d_i^2}{k+1} \times \frac{h_{ii}}{1-h_{ii}},
\]</span></p>
<p>donde <span class="math inline">\(d_i\)</span> corresponde al <strong>residual estandarizado</strong>.</p>
<p>Otra forma de obtener las distancias de Cook <span class="math inline">\(D_i\)</span> es ajustando el modelo de interés <code>mod</code> y luego aplicar la función <code>cooks.distance</code> sobre el modelo.</p>
<div class="cell" type="rmdnote">

<div class="rmdnote">
Son puntos influyentes las observaciones que presenten <span class="math inline">\(D_i&gt;1\)</span>.
</div>
</div>
<section id="ejemplo-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="ejemplo-2">Ejemplo:</h3>
<p>En este ejemplo se usará una base de datos que contiene medidas corporales para un grupo de estudiantes universitarios que vieron el curso de modelos de regresión en el año 2013. Abajo se muestra una figura ilustrativa de los datos.</p>
<p align="center">
<img src="images/medidas_cuerpo_upb.png" width="700">
</p>
<p>El objetivo es ajustar un modelo de regresión para explicar el peso promedio en función de la circunferencia de la muñeca, cuello y estatura. Luego de ajustar el modelo se deben identificar los posibles estudiantes influyentes y el efecto de ellos en el modelo.</p>
<p><strong>Solución</strong></p>
<p>Lo primero es cargar los datos en nuestra sesión de R.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="st">"https://raw.githubusercontent.com/fhernanb/datos/master/medidas_cuerpo2"</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="at">file=</span>url, <span class="at">sep=</span><span class="st">"</span><span class="sc">\t</span><span class="st">"</span>, <span class="at">header=</span><span class="cn">TRUE</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(datos, <span class="at">n=</span><span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Ano Semestre Peso Sexo Estatura circun_cuello circun_muneca
1 2020        1 47.6    F     1.57          29.5          13.9
2 2020        1 68.1    M     1.66          38.4          16.0
3 2020        1 68.0    M     1.90          36.5          16.6
4 2020        1 80.0    M     1.76          38.0          17.1
5 2020        1 68.1    M     1.83          38.0          17.1</code></pre>
</div>
</div>
<p>Antes de ajustar cualquier modelo es fundamental hacer un análisis descriptivo de los datos. Comenzaremos construyendo un diagrama de dispersión con <code>ggpairs</code>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"GGally"</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpairs</span>(datos[, <span class="fu">c</span>(<span class="st">"Peso"</span>, <span class="st">"Estatura"</span>, <span class="st">"circun_cuello"</span>, <span class="st">"circun_muneca"</span>)])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="11-diag2_files/figure-html/upb_01-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>De la figura anterior se observa que hay un punto que se aleja de la nube, es un estudiante que pesa un poco más de 100 kilogramos.</p>
<p>Vamos ahora a ajustar nuestro primer modelo.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Peso <span class="sc">~</span> Estatura <span class="sc">+</span> circun_cuello <span class="sc">+</span> circun_muneca, <span class="at">data=</span>datos)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Peso ~ Estatura + circun_cuello + circun_muneca, 
    data = datos)

Residuals:
    Min      1Q  Median      3Q     Max 
-12.277  -3.141  -0.364   2.980  20.065 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    -57.109     14.176  -4.029 0.000199 ***
Estatura        10.773     10.492   1.027 0.309674    
circun_cuello    2.302      0.387   5.949    3e-07 ***
circun_muneca    1.428      1.048   1.362 0.179546    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.822 on 48 degrees of freedom
Multiple R-squared:  0.7692,    Adjusted R-squared:  0.7548 
F-statistic: 53.32 on 3 and 48 DF,  p-value: 2.585e-15</code></pre>
</div>
</div>
<p>Como en la tabla anterior aparecen variables que nos son significativas vamos a realizar una selección de variables usando el paquete <strong>mixlm</strong> creado por <span class="citation" data-cites="R-mixlm">Liland (<a href="references.html#ref-R-mixlm" role="doc-biblioref">2025</a>)</span>. Vamos a realizar una selección de variables de manera que sólo queden variables significativas con un <span class="math inline">\(\alpha=0.04\)</span>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> mixlm<span class="sc">::</span><span class="fu">backward</span>(mod1, <span class="at">alpha=</span><span class="fl">0.04</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Backward elimination, alpha-to-remove: 0.04

Full model: Peso ~ Estatura + circun_cuello + circun_muneca

              Step    RSS    AIC  R2pred     Cp F value  Pr(&gt;F)  
Estatura         1 1662.6 186.17 0.71720 3.0543  1.0543 0.30967  
circun_muneca    2 1761.7 187.18 0.71701 3.9787  2.9212 0.09375 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Peso ~ circun_cuello, data = datos)

Residuals:
     Min       1Q   Median       3Q      Max 
-11.4526  -3.7980  -0.5279   3.6603  18.9962 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   -37.1552     8.4079  -4.419 5.33e-05 ***
circun_cuello   2.9002     0.2368  12.250  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

s: 5.936 on 50 degrees of freedom
Multiple R-squared: 0.7501,
Adjusted R-squared: 0.7451 
F-statistic: 150.1 on 1 and 50 DF,  p-value: &lt; 2.2e-16 </code></pre>
</div>
</div>
<p>En la siguiente tabla se comparan los modelos 1 y 2 ajustados hasta ahora.</p>
<p align="center">
<img src="images/tabla_1_2_upb.png" width="400">
</p>
<p>De la tabla anterior podemos destacar lo siguiente:</p>
<ul>
<li>El intercepto estimado cambia bastante.</li>
<li>En el modelo 2 la variable cuello aumenta su efecto.</li>
<li>El <span class="math inline">\(R^2\)</span> se mantiene constante.</li>
<li>La varianza de los errores disminuye, eso significa que el modelo 2 deja menos sin explicar.</li>
</ul>
<p>Vamos ahora a crear el diagrama de dispersión con el modelo ajustado.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Para construir el grafico de dispersion</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(datos, </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>     <span class="fu">plot</span>(<span class="at">x=</span>circun_cuello, <span class="at">y=</span>Peso, <span class="at">pch=</span><span class="dv">19</span>, <span class="at">las=</span><span class="dv">1</span>,</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">xlab=</span><span class="st">"Circunferencia cuello (cm)"</span>, <span class="at">ylab=</span><span class="st">"Peso (Kg)"</span>))</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Ahora agregamos la linea de tendencia</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(mod2, <span class="at">lwd=</span><span class="dv">3</span>, <span class="at">col=</span><span class="st">'blue2'</span>)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="co"># por ultimo un texto con la ecuacion o modelo ajustado</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x=</span><span class="dv">34</span>, <span class="at">y=</span><span class="dv">95</span>, <span class="fu">expression</span>(<span class="fu">hat</span>(Peso) <span class="sc">==</span> <span class="sc">-</span><span class="fl">44.61</span> <span class="sc">+</span> <span class="fl">3.10</span> <span class="sc">*</span> C.cuello), </span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">col=</span><span class="st">'blue3'</span> )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="11-diag2_files/figure-html/upb_02-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>De la figura anterior vemos que hay un estudiante (el de 100 kilos de peso) que está muy alejado de la recta de regresión.</p>
<p>Vamos a calcular las distancias de Cook para las observaciones del modelo 2 así:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cooks.distance</span>(mod2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>           1            2            3            4            5            6 
7.804662e-04 1.938685e-02 1.563287e-04 2.219833e-02 1.128458e-02 2.524701e-03 
           7            8            9           10           11           12 
4.092417e-03 1.222835e-01 7.151786e-04 1.149054e-03 4.808540e-01 3.722745e-02 
          13           14           15           16           17           18 
3.938290e-02 1.849408e-04 1.029180e-02 6.228690e-04 1.681916e-02 9.700850e-06 
          19           20           21           22           23           24 
7.536443e-03 1.538284e-03 6.643811e-03 7.225225e-03 3.624830e-03 1.331368e-02 
          25           26           27           28           29           30 
1.895684e-03 8.745440e-05 4.836285e-04 2.002813e-02 1.742378e-03 4.885748e-03 
          31           32           33           34           35           36 
6.336181e-04 1.163887e-02 1.529500e-02 5.686460e-04 7.534900e-03 1.800503e-02 
          37           38           39           40           41           42 
1.347941e-02 6.164670e-04 9.932676e-03 5.753702e-02 3.519145e-02 2.780173e-04 
          43           44           45           46           47           48 
5.921498e-03 4.435951e-03 2.649280e-03 2.559527e-02 3.105562e-02 2.775930e-04 
          49           50           51           52 
3.554232e-03 4.082713e-03 6.130210e-01 3.859845e-02 </code></pre>
</div>
</div>
<p>Es mejor representar las distancias de Cook en forma gráfica para identificar los posible puntos influyentes así:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>cutoff <span class="ot">&lt;-</span> <span class="dv">4</span> <span class="sc">/</span> (<span class="dv">26-2-2</span>)  <span class="co"># Cota</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod2, <span class="at">which=</span><span class="dv">4</span>, <span class="at">cook.levels=</span>cutoff, <span class="at">las=</span><span class="dv">1</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span>cutoff, <span class="at">lty=</span><span class="st">"dashed"</span>, <span class="at">col=</span><span class="st">"dodgerblue2"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="11-diag2_files/figure-html/upb_03-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>De esta figura es claro que las observaciones 11 y 8 tienen <span class="math inline">\(D_i\)</span> por encima de la cota y se consideran observaciones influyentes.</p>
<p>Otra forma de dibujar las distancias de Cook es por medio de la función <code>influenceIndexPlot</code> del paquete <strong>car</strong>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">influenceIndexPlot</span>(mod2, <span class="at">vars=</span><span class="st">"Cook"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="11-diag2_files/figure-html/cook_estudiantes_upb-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>Ahora vamos a revisar los residuales del modelo 2.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod2, <span class="at">col=</span><span class="st">'deepskyblue4'</span>, <span class="at">pch=</span><span class="dv">19</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="11-diag2_files/figure-html/upb_04-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>De la anterior figura vemos que las observaciones 8, 11 y 13 son identificadas por tener valores de residuales grandes.</p>
<p>Vamos ahora a identificar las observaciones 8, 11, 12 y 13 en un diagrama de dispersión.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="11-diag2_files/figure-html/upb_05-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>La observación 11 es un hombre que pesa más de 100 kilos y que solo mide 1.79 metros. Las observaciones 8, 12 y 13 son mujeres con las mayores diferencias entre <span class="math inline">\(y_i\)</span> y <span class="math inline">\(\hat{y}_i\)</span>, para ellas el modelo sobreestima el peso corporal.</p>
<p>En la siguiente tabla se muestran los resultados de ajustar nuevamente el modelo 2 bajo tres situaciones: con todas las observaciones, sin la observación 11 y sin las observaciones 8, 11, 12 y 13. De la tabla vemos que la observación 11 es muy influyente, al sacar esa observación el modelo aumenta su <span class="math inline">\(R^2\)</span> y disminuye su <span class="math inline">\(\sigma^2\)</span>. De la última columna se observa el mismo comportamiento, <span class="math inline">\(R^2\)</span> aumenta y disminuye su <span class="math inline">\(\sigma^2\)</span> al sacar todas las observaciones sospechosas.</p>
<p align="center">
<img src="images/tabla_2_sin_obs_inf_upb.png" width="400">
</p>
<p>Pero, ¿cuál modelo debo usar como modelo final? ¿El modelo 2, el modelo 2 sin la obs 11 o el modelo 2 sin las obs 8, 11, 12 y 13?</p>
<p>Lo que se recomienda es que el analista se asesore de un experto en el área de aplicación para que juntos estudien esas observaciones sospechosas. Si hay una razón de peso para considerarlas como observaciones atípicas, ellas deben salir del modelo. Si por el contrario, no hay nada raro con las observaciones, ellas deben seguir en el modelo.</p>
<p align="center">
<img src="images/revisar.png" width="300">
</p>
<div class="cell" type="rmdwarning">

<div class="rmdwarning">
Las observaciones sospechosas NO se deben sacar inmediatamente del modelo. Antes se deben estudiar para ver si hay algo raro con ellas, en caso afirmativo se sacan de la base y se ajusta nuevamente el modelo.
</div>
</div>
<div class="cell" type="rmdnote">

<div class="rmdnote">
<p>Una observación influyente NO es una observación mala en el modelo. Al contrario, ella es una observación clave en el ajuste porque “lidera” la estimación.</p>
Una observación que no es influyente es una observación que estando presente o no, el modelo ajustado no se ve afectado.
</div>
</div>
</section>
</section>
<section id="dffits" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="dffits">DFFITS</h2>
<p>Es una medida de la influencia de la <span class="math inline">\(i\)</span>-ésima observación sobre el valor predicho o ajustado, la expresión para calcularla es la siguiente:</p>
<p><span class="math display">\[
DFFITS_i = \frac{\hat{y}_i - \hat{y}_{i(i)}}{\sqrt{s_{(i)}^2 h_{ii}}}.
\]</span></p>
<p>Una observación será influyente si <span class="math inline">\(|DFFITS| &gt; 2 \sqrt{p/n}\)</span>.</p>
<p>La función en R para obtener los <span class="math inline">\(DFFITS_i\)</span> es <code>dffits</code>.</p>
</section>
<section id="dfbetas" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="dfbetas">DFBETAS</h2>
<p>Es una medida que indica cuánto cambia el coeficiente de regresión, en unidades de desviación estándar, si se omitiera la <span class="math inline">\(i\)</span>-ésima observación.</p>
<p><span class="math display">\[
DFBETAS_{i,j} = \frac{\hat{\beta}_j - \hat{\beta}_{j(i)}}{\sqrt{s_{(i)}^2 C_{jj}}},
\]</span></p>
<p>donde <span class="math inline">\(C_{jj}\)</span> es <span class="math inline">\(j\)</span>-ésimo elemento de la diagonal de <span class="math inline">\((\boldsymbol{X}^\top \boldsymbol{X})^{-1}\)</span>.</p>
<p>Una observación será influyente si <span class="math inline">\(|DFBETAS| &gt; 2 \sqrt{n}\)</span>.</p>
<p>La función en R para obtener los <span class="math inline">\(DFBETAS_{i,j}\)</span> es <code>dfbetas</code>.</p>
<section id="ejemplo-3" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="ejemplo-3">Ejemplo</h3>
<p>Considere los datos que se muestran a continuación y ajuste un modelo de regresión para explicar <span class="math inline">\(y\)</span> en función de <span class="math inline">\(x\)</span>. Luego identifique las observaciones influyentes usando las medidas DFFITS y DFBETAS.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">5</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">7</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">9</span>, <span class="dv">8</span>, <span class="dv">7</span>, <span class="dv">19</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Solución</strong></p>
<p>Vamos a crear un diagrama de dispersión para los datos del ejemplo.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x=</span>x, <span class="at">y=</span>y, <span class="at">pch=</span><span class="dv">19</span>, <span class="at">col=</span><span class="st">"tomato"</span>, <span class="at">las=</span><span class="dv">1</span>)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, <span class="at">x=</span>x<span class="fl">-0.1</span>, <span class="at">y=</span>y, <span class="at">cex=</span><span class="fl">0.5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="11-diag2_files/figure-html/ejem_dffits01-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="384"></p>
</figure>
</div>
</div>
</div>
<p>Lo siguiente es ajustar el modelo de regresión de interés.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Vamos a calcular DFFITS usando la función <code>dffits</code> sobre el modelo ya ajustado.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dffits</span>(mod)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         1          2          3          4          5 
 0.5838725 -0.7757081  0.4112718 -0.4420348  5.8081955 </code></pre>
</div>
</div>
<p>De la salida anterior vemos que la observación 5 es la única que tiene un <span class="math inline">\(|DFFITS|\)</span> mayor a <span class="math inline">\(2\sqrt{\frac{p}{n}}=2\sqrt{\frac{2}{5}}=1.26\)</span>. Por esa razón podemos considerar a la observación 5 como una observación influyente.</p>
<p>Vamos a calcular DFBETAS usando la función <code>dfbetas</code> sobre el modelo ya ajustado.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dfbetas</span>(mod)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)           x
1  0.56194908 -0.45993179
2  0.03603076 -0.32706727
3  0.34558823 -0.23527935
4 -0.21367111  0.05104178
5 -3.42671836  4.94865731</code></pre>
</div>
</div>
<p>De la salida anterior vemos nuevamente que la observación 5 tiene la mayor influencia sobre <span class="math inline">\(\hat{\beta}_0\)</span> y sobre <span class="math inline">\(\hat{\beta}_1\)</span>. Como ambos valores de <span class="math inline">\(|DFBETAS|\)</span> son mayores a <span class="math inline">\(\frac{2}{\sqrt{n}}=\frac{2}{\sqrt{5}}=0.89\)</span>, podemos considerar a la observación 5 como una observación influyente.</p>
<p>Existe otra función llamda <code>dfbeta</code> (sin la letra <strong>s</strong>), veamos para qué sirve esta función.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dfbeta</span>(mod)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)           x
1  1.93127413 -0.34826255
2  0.09555985 -0.19111969
3  1.16424116 -0.17463617
4 -0.67017865  0.03527256
5 -4.69729730  1.49459459</code></pre>
</div>
</div>
<p>En conclusión,</p>
<ol type="1">
<li>La función <code>dfbetas</code> entrega <span class="math inline">\(\frac{\hat{\beta}_j - \hat{\beta}_{j(i)}}{\sqrt{s_{(i)}^2 C_{jj}}}\)</span>.</li>
<li>La función <code>dfbeta</code> entrega <span class="math inline">\(\hat{\beta}_j - \hat{\beta}_{j(i)}\)</span>.</li>
</ol>
</section>
</section>
<section id="estadística-press-y-r2-de-predicción" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="estadística-press-y-r2-de-predicción">Estadística PRESS y <span class="math inline">\(R^2\)</span> de predicción</h2>
<p>Es una medida de lo BIEN que el modelo logra predecir <span class="math inline">\(\hat{y}\)</span> para nuevas observaciones.</p>
<p><span class="math display">\[
PRESS = \sum_{i=1}^{n} e_{(i)}^2 = \sum_{i=1}^{n} (y_i - \hat{y}_{(i)})^2 = \sum_{i=1}^{n} \left( \frac{e_i}{1-h_{ii}} \right)^2
\]</span></p>
<p>El <span class="math inline">\(R^2\)</span> de predicción es una medida del porcentaje de la variabilidad explicada por el modelo para nuevas observaciones. El <span class="math inline">\(R^2\)</span> de predicción se define en función de la estadística PRESS así:</p>
<p><span class="math display">\[
R^2 \, \text{de predicción} = 1 - \frac{PRESS}{SST}
\]</span></p>
<p>Las funciones mostradas abajo fueron creadas por <a href="https://gist.github.com/tomhopper/8c204d978c4a0cbcb8c0">Tom Hopper</a> y sirven para obtener la estadística PRESS y el <span class="math inline">\(R^2\)</span> de predicción.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>PRESS <span class="ot">&lt;-</span> <span class="cf">function</span>(linear.model) {</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># calculate the predictive residuals</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  pr <span class="ot">&lt;-</span> <span class="fu">residuals</span>(linear.model) <span class="sc">/</span> (<span class="dv">1</span><span class="sc">-</span><span class="fu">lm.influence</span>(linear.model)<span class="sc">$</span>hat)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># calculate the PRESS</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  PRESS <span class="ot">&lt;-</span> <span class="fu">sum</span>(pr<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(PRESS)</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>pred_r_squared <span class="ot">&lt;-</span> <span class="cf">function</span>(linear.model) {</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>  <span class="co">#' Use anova() to get the sum of squares for the linear model</span></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>  lm.anova <span class="ot">&lt;-</span> <span class="fu">anova</span>(linear.model)</span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>  <span class="co">#' Calculate the total sum of squares</span></span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>  tss <span class="ot">&lt;-</span> <span class="fu">sum</span>(lm.anova<span class="sc">$</span><span class="st">'Sum Sq'</span>)</span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Calculate the predictive R^2</span></span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a>  pred.r.squared <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">-</span><span class="fu">PRESS</span>(linear.model)<span class="sc">/</span>(tss)</span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(pred.r.squared)</span>
<span id="cb38-17"><a href="#cb38-17" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="ejemplo-4" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="ejemplo-4">Ejemplo</h3>
<p>Como ilustración vamos a usar los datos del ejemplo 3.1 del libro de <span class="citation" data-cites="mpv06">(<a href="references.html#ref-mpv06" role="doc-biblioref">Montgomery 2006</a>)</span>. En el ejemplo 3.1 los autores ajustaron un modelo de regresión lineal múltiple para explicar el <strong>Tiempo</strong> necesario para que un trabajador haga el mantenimiento y surta una máquina dispensadora de refrescos en función de las variables <strong>Número de Cajas</strong> y <strong>Distancia</strong>.</p>
<p align="center">
<img src="images/ilustracion_refrescos.png" width="600">
</p>
<p>¿Cuál es el valor de la estadística PRESS y del <span class="math inline">\(R^2\)</span> de predicción?</p>
<p><strong>Solución</strong></p>
<p>Los datos del ejemplo están disponibles en el paquete <strong>MPV</strong> (por los apellidos de los autores). A continuación el código para cargar los datos y ajustar el modelo de interés.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(MPV)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(softdrink) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'tiempo'</span>, <span class="st">'cantidad'</span>, <span class="st">'distancia'</span>)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(tiempo <span class="sc">~</span> cantidad <span class="sc">+</span> distancia, <span class="at">data=</span>softdrink)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>A continuación se muestran las dos medidas de interés.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">PRESS</span>(mod)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 459.0393</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pred_r_squared</span>(mod)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9206438</code></pre>
</div>
</div>
<p>De la salida anterior se observa que el <span class="math inline">\(R^2\)</span> de predicción toma un valor de 0.9206, esto indica que el modelo <code>mod</code> tiene una buena capacidad de predicción para nuevas observaciones.</p>
</section>
</section>
<section id="valores-de-corte-para-diagnósticos" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="valores-de-corte-para-diagnósticos">Valores de corte para diagnósticos</h2>
<p><span class="citation" data-cites="fox2015applied">Fox (<a href="references.html#ref-fox2015applied" role="doc-biblioref">2015</a>)</span> en la sección 11.5 hace una recopilación de los puntos de corte que se podrían usar para identificar observaciones con alguna anomalía al ajustar un modelo de regresión. En el siguiente listado se muestran esos puntos de corte pero se recomienda al lector para que revise <span class="citation" data-cites="fox2015applied">Fox (<a href="references.html#ref-fox2015applied" role="doc-biblioref">2015</a>)</span> y conozca unas recomendaciones adicionales sobre los puntos de corte.</p>
<ul>
<li>Observaciones con valores de <span class="math inline">\(h_{ii}\)</span> que excedan dos veces el valor <span class="math inline">\(\bar{h} = (k+1)/n\)</span> podrían ser observaciones atípicas o outliers. Este punto de corte se obtiene como una aproximación para identificar el 5% de las observaciones más extremas si las <span class="math inline">\(X\)</span>’s se distribuyen normal multivariada con <span class="math inline">\(k\)</span> y <span class="math inline">\(n-k-1\)</span> grandes (<span class="math inline">\(k\)</span> se refiere al número de <span class="math inline">\(\beta\)</span>’s diferentes al intercepto).</li>
<li>Como los residuales estandarizados <span class="math inline">\(d_i\)</span>, tienen media cero y varianza aproximadamente unitaria, un residual estandarizado grande, <span class="math inline">\(|d_i| &gt; 3\)</span>, indica que se trata de un valor atípico potencial.</li>
<li>Como los residuales studentizados <span class="math inline">\(r_i\)</span> tienen distribución <span class="math inline">\(t\)</span>-student, es decir, <span class="math inline">\(t_{n-k-2}\)</span>, se podrían considerar como posibles residual atípico aquel cuyo valor cumpla <span class="math inline">\(|r_i| &gt; 2\)</span>.</li>
<li>Una observación con un residual PRESS grande se puede considerar como una observación influyente.</li>
<li>Una observación se puede considerar como influyente si su distancia de Cook cumple que <span class="math inline">\(D_i &gt; 4/(n-k-1)\)</span>, donde <span class="math inline">\(k\)</span> se refiere al número de <span class="math inline">\(\beta\)</span>’s diferentes al intercepto.</li>
<li>Una observación se puede considerar como influyente si valor de DFFITS cumple que <span class="math inline">\(|DFFITS_i| &gt; 2 \sqrt{\frac{k+1}{n-k-1}}\)</span>.</li>
</ul>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-fox2015applied" class="csl-entry" role="listitem">
Fox, John. 2015. <em>Applied Regression Analysis and Generalized Linear Models</em>. Sage Publications.
</div>
<div id="ref-R-car" class="csl-entry" role="listitem">
Fox, John, Sanford Weisberg, and Brad Price. 2026. <em>Car: Companion to Applied Regression</em>. <a href="https://github.com/bprice2652/car_repo">https://github.com/bprice2652/car_repo</a>.
</div>
<div id="ref-R-mixlm" class="csl-entry" role="listitem">
Liland, Kristian Hovde. 2025. <em>Mixlm: Mixed Model ANOVA and Statistics for Education</em>. <a href="https://github.com/khliland/mixlm/">https://github.com/khliland/mixlm/</a>.
</div>
<div id="ref-mpv06" class="csl-entry" role="listitem">
Montgomery, E. &amp; Vining, D. &amp; Peck. 2006. <em>Introducción Al Análisis de Regresión Lineal</em>. 3ed ed. Cecsa.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./10-diag1.html" class="pagination-link" aria-label="Diagnósticos parte I">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Diagnósticos parte I</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./12-ph-homoce.html" class="pagination-link" aria-label="Pruebas de Homocedasticidad">
        <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Pruebas de Homocedasticidad</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>