<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>16&nbsp; Selección de variables – Análisis de regresión con R</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./17-feature_selection.html" rel="next">
<link href="./15-all_possible_reg.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-0d3ac16015dd0859924b68075192f47b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./16-selecvar.html"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Selección de variables</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Análisis de regresión con R</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefacio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-rls.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Regresión lineal simple</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-transf.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Transformaciones</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-rlm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Regresión lineal múltiple</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-predict.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Predicción</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-simul.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Simulación</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-ic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Intervalos de confianza</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-var_cuali.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Modelos con variables cualitativas</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-ph1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Pruebas de hipótesis parte I</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-ph2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Pruebas de hipótesis parte II</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-diag1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Diagnósticos parte I</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-diag2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Diagnósticos parte II</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-ph-homoce.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Pruebas de Homocedasticidad</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-ph-indep.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Pruebas de independencia de los errores</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-mod_poli.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Modelos polinomiales</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-all_possible_reg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Todas las regresiones posibles</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-selecvar.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Selección de variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-feature_selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Feature selection</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-multicoli.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Multicolinealidad</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-coefEstandarizados.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Regresión con coeficientes de regresión estandarizados</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-algebramatricial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Algebra matricial con R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21-Wilkinson-Rogers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Notación de Wilkinson y Rogers</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./22-xy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">¿Cómo obtener la matriz <span class="math inline">\(\boldsymbol{X}\)</span> y el vector <span class="math inline">\(\boldsymbol{y}\)</span>?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./23-behind.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Otros aspectos importantes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./24-pasos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Pasos para construir modelos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./25-misspecification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Mala especificación</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#akaike-information-criterion-aic" id="toc-akaike-information-criterion-aic" class="nav-link active" data-scroll-target="#akaike-information-criterion-aic">Akaike Information Criterion (<span class="math inline">\(AIC\)</span>)</a></li>
  <li><a href="#funciones-loglik-y-aic" id="toc-funciones-loglik-y-aic" class="nav-link" data-scroll-target="#funciones-loglik-y-aic">Funciones <code>logLik</code> y <code>AIC</code></a></li>
  <li><a href="#métodos" id="toc-métodos" class="nav-link" data-scroll-target="#métodos">Métodos</a></li>
  <li><a href="#función-stepaic" id="toc-función-stepaic" class="nav-link" data-scroll-target="#función-stepaic">Función <code>stepAIC</code></a>
  <ul class="collapse">
  <li><a href="#ejemplo" id="toc-ejemplo" class="nav-link" data-scroll-target="#ejemplo">Ejemplo</a></li>
  <li><a href="#aplicación-del-método-backward" id="toc-aplicación-del-método-backward" class="nav-link" data-scroll-target="#aplicación-del-método-backward">Aplicación del método <strong>backward</strong></a></li>
  <li><a href="#aplicación-del-método-forward" id="toc-aplicación-del-método-forward" class="nav-link" data-scroll-target="#aplicación-del-método-forward">Aplicación del método <strong>forward</strong></a></li>
  <li><a href="#aplicación-del-método-both" id="toc-aplicación-del-método-both" class="nav-link" data-scroll-target="#aplicación-del-método-both">Aplicación del método <strong>both</strong></a></li>
  <li><a href="#ejercicios" id="toc-ejercicios" class="nav-link" data-scroll-target="#ejercicios">Ejercicios</a></li>
  </ul></li>
  <li><a href="#funciones-addterm-y-dropterm" id="toc-funciones-addterm-y-dropterm" class="nav-link" data-scroll-target="#funciones-addterm-y-dropterm">Funciones <code>addterm</code> y <code>dropterm</code></a>
  <ul class="collapse">
  <li><a href="#ejemplo-1" id="toc-ejemplo-1" class="nav-link" data-scroll-target="#ejemplo-1">Ejemplo</a></li>
  </ul></li>
  <li><a href="#paquete-mixlm" id="toc-paquete-mixlm" class="nav-link" data-scroll-target="#paquete-mixlm">Paquete <strong>mixlm</strong></a>
  <ul class="collapse">
  <li><a href="#ejemplo-2" id="toc-ejemplo-2" class="nav-link" data-scroll-target="#ejemplo-2">Ejemplo</a></li>
  </ul></li>
  <li><a href="#paquete-leaps" id="toc-paquete-leaps" class="nav-link" data-scroll-target="#paquete-leaps">Paquete <strong>leaps</strong></a>
  <ul class="collapse">
  <li><a href="#ejemplo-3" id="toc-ejemplo-3" class="nav-link" data-scroll-target="#ejemplo-3">Ejemplo</a></li>
  </ul></li>
  <li><a href="#funciones-para-el-curso-estadística-ii" id="toc-funciones-para-el-curso-estadística-ii" class="nav-link" data-scroll-target="#funciones-para-el-curso-estadística-ii">Funciones para el curso Estadística II</a>
  <ul class="collapse">
  <li><a href="#ejemplo-4" id="toc-ejemplo-4" class="nav-link" data-scroll-target="#ejemplo-4">Ejemplo</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="selec" class="quarto-section-identifier"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Selección de variables</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>En este capítulo se muestra como realizar selección de variables en un modelo de regresión lineal.</p>
<section id="akaike-information-criterion-aic" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="akaike-information-criterion-aic">Akaike Information Criterion (<span class="math inline">\(AIC\)</span>)</h2>
<p>El <span class="math inline">\(AIC\)</span> se define como:</p>
<p><span class="math display">\[AIC = - 2 \times logLik + k \times n_{par},\]</span></p>
<p>donde <span class="math inline">\(logLik\)</span> corresponde al valor de log-verosimilitud del modelo para el vector de parámetros <span class="math inline">\(\hat{\Theta}\)</span>, <span class="math inline">\(k\)</span> es un valor de penalización por el exceso de parámetros y <span class="math inline">\(n_{par}\)</span> corresponde al número de parámetros del modelo.</p>
<p>Se debe recordar siempre que:</p>
<ul>
<li>El mejor modelo es aquel que <span class="math inline">\(logLik\)</span> ↑.</li>
<li>El mejor modelo es aquel que <span class="math inline">\(AIC\)</span> ↓.</li>
</ul>
<p>Cuando el valor de penalización <span class="math inline">\(k=\log(n)\)</span> entonces el <span class="math inline">\(AIC\)</span> se llamada en <span class="math inline">\(BIC\)</span> o <span class="math inline">\(SBC\)</span> (Schwarz’s Bayesian criterion).</p>
</section>
<section id="funciones-loglik-y-aic" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="funciones-loglik-y-aic">Funciones <code>logLik</code> y <code>AIC</code></h2>
<p>La función <code>logLik</code> sirve para obtener el valor de log-verosimilitud de un modelo y la función <code>AIC</code> entrega el Akaike Information Criterion. La estructura de ambas funciones se muestra a continuación.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">logLik</span>(object)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(object, <span class="at">k=</span><span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="métodos" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="métodos">Métodos</h2>
<p>Los métodos para realizar selcción de variables se pueden clasificar de la siguiente manera:</p>
<ol type="1">
<li>Todas las regresiones posibles.</li>
<li>Selección de variables.
<ul>
<li>Forward</li>
<li>Backward</li>
</ul></li>
</ol>
<p>A continuación una imagen ilustrativa para entender ambos métodos.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/forward_backward.png" class="img-fluid figure-img" width="686"></p>
<figcaption>Ilustración de los métodos.</figcaption>
</figure>
</div>
</div>
</div>
<ul>
<li>Un término ingresa al modelo si su presencia disminuye el <span class="math inline">\(AIC\)</span>.</li>
<li>Un términa sale del modelo si su ausencia disminuye el <span class="math inline">\(AIC\)</span>.</li>
</ul>
</section>
<section id="función-stepaic" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="función-stepaic">Función <code>stepAIC</code></h2>
<p>La función <code>stepAIC</code> del paquete <strong>MASS</strong> <span class="citation" data-cites="R-MASS">(<a href="references.html#ref-R-MASS" role="doc-biblioref">Ripley and Venables 2025</a>)</span> es útil para hacer selección de variables en un modelo de regresión. La estructura de la función se muestra a continuación.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stepAIC</span>(object, scope, <span class="at">scale =</span> <span class="dv">0</span>,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">direction =</span> <span class="fu">c</span>(<span class="st">"both"</span>, <span class="st">"backward"</span>, <span class="st">"forward"</span>),</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">trace =</span> <span class="dv">1</span>, <span class="at">keep =</span> <span class="cn">NULL</span>, <span class="at">steps =</span> <span class="dv">1000</span>, <span class="at">use.start =</span> <span class="cn">FALSE</span>,</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">k =</span> <span class="dv">2</span>, ...)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Algunos de los argumentos son:</p>
<ul>
<li><code>object</code>: un objeto con un modelo.</li>
<li><code>scope</code>: fórmula(s) con los límites de búsqueda.</li>
<li><code>direction</code>: los posibles valores son <code>both</code>, <code>backward</code>, <code>forward</code>.</li>
<li><code>trace</code>: valor lógico para indicar si se desea ver el paso a paso de la selección.</li>
<li><code>k</code>: valor de penalidad, por defecto es 2.</li>
</ul>
<section id="ejemplo" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="ejemplo">Ejemplo</h3>
<p>En este ejemplo se busca encontrar un modelo de regresion lineal que explique la variable respuesta <span class="math inline">\(y\)</span> en función de las covariables <span class="math inline">\(x_1\)</span> a <span class="math inline">\(x_{11}\)</span>, los datos provienen del ejercicio 9.5 del libro de <a href="https://www.amazon.com/Introduccion-analisis-regresion-lineal-Spanish/dp/9702403278">Montgomery, Peck and Vining (2003)</a>.</p>
<p>A continuación se muestra el encabezado de la base de datos y la definición de las variables.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/tableb3.PNG" class="img-fluid figure-img" width="786"></p>
<figcaption>Ilustración de la base de datos.</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Nota</strong>: Type of transmission (1=automatic, 0=manual).</p>
<p><strong>Solución</strong></p>
<p>Antes de iniciar es necesario revisar si hay <code>NA's</code> y eliminarlos.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MPV)  <span class="co"># Aqui estan los datos</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>table.b3[<span class="dv">22</span><span class="sc">:</span><span class="dv">26</span>, ] <span class="co"># Can you see the missing values?</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       y    x1  x2  x3  x4   x5 x6 x7    x8   x9  x10 x11
22 21.47 360.0 180 290 8.4 2.45  2  3 214.2 76.3 4250   1
23 16.59 400.0 185  NA 7.6 3.08  4  3 196.0 73.0 3850   1
24 31.90  96.9  75  83 9.0 4.30  2  5 165.2 61.8 2275   0
25 29.40 140.0  86  NA 8.0 2.92  2  4 176.4 65.4 2150   0
26 13.27 460.0 223 366 8.0 3.00  4  3 228.0 79.8 5430   1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> table.b3[<span class="sc">-</span><span class="fu">c</span>(<span class="dv">23</span>, <span class="dv">25</span>), ]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>El objeto <code>datos</code> tiene la base de datos sin las líneas con <code>NA</code>, lo mismo se hubiese podido realizar usando la función <code>na.omit</code>.</p>
</section>
<section id="aplicación-del-método-backward" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="aplicación-del-método-backward">Aplicación del método <strong>backward</strong></h3>
<p>Vamos a crear un modelo <em>saturado</em>, es decir, el modelo mayor a considerar.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>full.model <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> ., <span class="at">data=</span>datos)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(full.model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ ., data = datos)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.3441 -1.6711 -0.4486  1.4906  5.2508 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept) 17.339838  30.355375   0.571   0.5749  
x1          -0.075588   0.056347  -1.341   0.1964  
x2          -0.069163   0.087791  -0.788   0.4411  
x3           0.115117   0.088113   1.306   0.2078  
x4           1.494737   3.101464   0.482   0.6357  
x5           5.843495   3.148438   1.856   0.0799 .
x6           0.317583   1.288967   0.246   0.8082  
x7          -3.205390   3.109185  -1.031   0.3162  
x8           0.180811   0.130301   1.388   0.1822  
x9          -0.397945   0.323456  -1.230   0.2344  
x10         -0.005115   0.005896  -0.868   0.3971  
x11          0.638483   3.021680   0.211   0.8350  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.227 on 18 degrees of freedom
Multiple R-squared:  0.8355,    Adjusted R-squared:  0.7349 
F-statistic:  8.31 on 11 and 18 DF,  p-value: 5.231e-05</code></pre>
</div>
</div>
<p>De la tabla anterior se puede pensar en que hay un efecto de <span style="color:red">enmascaramiento</span> entre las variables ya que ninguna parece significativa marginalmente.</p>
<p>Se usa la función <code>stepAIC</code> y se elije <code>trace=TRUE</code> para obtener detalles del proceso de selección.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)  <span class="co"># Para poder usar la funcion stepAIC</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>modback <span class="ot">&lt;-</span> <span class="fu">stepAIC</span>(full.model, <span class="at">trace=</span><span class="cn">TRUE</span>, <span class="at">direction=</span><span class="st">"backward"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=78.96
y ~ x1 + x2 + x3 + x4 + x5 + x6 + x7 + x8 + x9 + x10 + x11

       Df Sum of Sq    RSS    AIC
- x11   1     0.465 187.87 77.036
- x6    1     0.632 188.03 77.063
- x4    1     2.418 189.82 77.346
- x2    1     6.462 193.86 77.979
- x10   1     7.836 195.24 78.190
- x7    1    11.065 198.47 78.683
&lt;none&gt;              187.40 78.962
- x9    1    15.758 203.16 79.384
- x3    1    17.770 205.17 79.679
- x1    1    18.736 206.14 79.820
- x8    1    20.047 207.45 80.011
- x5    1    35.864 223.26 82.215

Step:  AIC=77.04
y ~ x1 + x2 + x3 + x4 + x5 + x6 + x7 + x8 + x9 + x10

       Df Sum of Sq    RSS    AIC
- x6    1     0.536 188.40 75.121
- x4    1     2.363 190.23 75.411
- x2    1     6.642 194.51 76.078
- x10   1     7.985 195.85 76.285
&lt;none&gt;              187.87 77.036
- x7    1    14.124 201.99 77.211
- x9    1    16.914 204.78 77.622
- x3    1    17.815 205.68 77.754
- x1    1    18.280 206.15 77.822
- x8    1    20.301 208.17 78.114
- x5    1    36.370 224.24 80.345

Step:  AIC=75.12
y ~ x1 + x2 + x3 + x4 + x5 + x7 + x8 + x9 + x10

       Df Sum of Sq    RSS    AIC
- x4    1     3.451 191.85 73.666
- x2    1     6.932 195.33 74.205
- x10   1     9.351 197.75 74.574
&lt;none&gt;              188.40 75.121
- x7    1    14.473 202.87 75.342
- x3    1    17.802 206.20 75.830
- x9    1    18.146 206.55 75.880
- x1    1    18.780 207.18 75.972
- x8    1    21.244 209.65 76.326
- x5    1    39.332 227.73 78.809

Step:  AIC=73.67
y ~ x1 + x2 + x3 + x5 + x7 + x8 + x9 + x10

       Df Sum of Sq    RSS    AIC
- x2    1    10.780 202.63 73.306
- x7    1    11.113 202.97 73.355
&lt;none&gt;              191.85 73.666
- x10   1    14.988 206.84 73.923
- x1    1    16.602 208.46 74.156
- x9    1    18.072 209.92 74.366
- x3    1    21.314 213.17 74.826
- x8    1    28.835 220.69 75.867
- x5    1    40.323 232.18 77.389

Step:  AIC=73.31
y ~ x1 + x3 + x5 + x7 + x8 + x9 + x10

       Df Sum of Sq    RSS    AIC
- x7    1    10.457 213.09 72.815
- x3    1    10.595 213.23 72.835
- x1    1    11.998 214.63 73.032
- x9    1    12.643 215.28 73.122
- x10   1    13.887 216.52 73.295
&lt;none&gt;              202.63 73.306
- x8    1    27.665 230.30 75.145
- x5    1    30.191 232.82 75.472

Step:  AIC=72.82
y ~ x1 + x3 + x5 + x8 + x9 + x10

       Df Sum of Sq    RSS    AIC
- x3    1    4.8720 217.96 71.494
- x9    1    5.2049 218.29 71.539
- x1    1    5.3212 218.41 71.555
&lt;none&gt;              213.09 72.815
- x10   1   18.3677 231.46 73.296
- x5    1   23.3458 236.44 73.934
- x8    1   26.0316 239.12 74.273

Step:  AIC=71.49
y ~ x1 + x5 + x8 + x9 + x10

       Df Sum of Sq    RSS    AIC
- x1    1     0.765 218.73 69.599
- x9    1     5.863 223.82 70.290
&lt;none&gt;              217.96 71.494
- x10   1    20.291 238.25 72.164
- x5    1    23.020 240.98 72.506
- x8    1    31.634 249.59 73.559

Step:  AIC=69.6
y ~ x5 + x8 + x9 + x10

       Df Sum of Sq    RSS    AIC
- x9    1     5.097 223.82 68.290
&lt;none&gt;              218.73 69.599
- x5    1    40.404 259.13 72.684
- x8    1    57.407 276.13 74.591
- x10   1   135.105 353.83 82.029

Step:  AIC=68.29
y ~ x5 + x8 + x10

       Df Sum of Sq    RSS    AIC
&lt;none&gt;              223.82 68.290
- x5    1    36.314 260.14 70.800
- x8    1    52.960 276.78 72.661
- x10   1   194.838 418.66 85.076</code></pre>
</div>
</div>
<p>Para obtener un resumen del proceso se usa:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>modback<span class="sc">$</span>anova</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Stepwise Model Path 
Analysis of Deviance Table

Initial Model:
y ~ x1 + x2 + x3 + x4 + x5 + x6 + x7 + x8 + x9 + x10 + x11

Final Model:
y ~ x5 + x8 + x10


   Step Df   Deviance Resid. Df Resid. Dev      AIC
1                            18   187.4007 78.96155
2 - x11  1  0.4648362        19   187.8655 77.03587
3  - x6  1  0.5356445        20   188.4012 75.12128
4  - x4  1  3.4514854        21   191.8526 73.66591
5  - x2  1 10.7796848        22   202.6323 73.30587
6  - x7  1 10.4571693        23   213.0895 72.81545
7  - x3  1  4.8720101        24   217.9615 71.49363
8  - x1  1  0.7654631        25   218.7270 69.59881
9  - x9  1  5.0970905        26   223.8241 68.28989</code></pre>
</div>
</div>
<p>Para ver la tabla de resultados del modelo <code>modback</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modback)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x5 + x8 + x10, data = datos)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.6101 -1.9868 -0.6613  2.0369  5.8811 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  4.590404  11.771925   0.390   0.6998    
x5           2.597240   1.264562   2.054   0.0502 .  
x8           0.217814   0.087817   2.480   0.0199 *  
x10         -0.009485   0.001994  -4.757 6.38e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.934 on 26 degrees of freedom
Multiple R-squared:  0.8035,    Adjusted R-squared:  0.7808 
F-statistic: 35.44 on 3 and 26 DF,  p-value: 2.462e-09</code></pre>
</div>
</div>
</section>
<section id="aplicación-del-método-forward" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="aplicación-del-método-forward">Aplicación del método <strong>forward</strong></h3>
<p>Para aplicar este metodo se debe crear un modelo vacío (<code>empty.model</code>) del cual iniciará el proceso. Es necesario definir un punto final de búsqueda, ese punto es una fórmula que en este caso llamaremos <code>horizonte</code>. A continuación el codigo.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>empty.model <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data=</span>datos)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>horizonte <span class="ot">&lt;-</span> <span class="fu">formula</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x2 <span class="sc">+</span> x3 <span class="sc">+</span> x4 <span class="sc">+</span> x5 <span class="sc">+</span> x6 <span class="sc">+</span> x7 <span class="sc">+</span> x8 <span class="sc">+</span> x9 <span class="sc">+</span> x10 <span class="sc">+</span> x11)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Se usa la función <code>stepAIC</code> y se elije <code>trace=FALSE</code> para que NO se muestren los detalles del proceso de selección.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>modforw <span class="ot">&lt;-</span> <span class="fu">stepAIC</span>(empty.model, <span class="at">trace=</span><span class="cn">FALSE</span>, <span class="at">direction=</span><span class="st">"forward"</span>, <span class="at">scope=</span>horizonte)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>modforw<span class="sc">$</span>anova</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Stepwise Model Path 
Analysis of Deviance Table

Initial Model:
y ~ 1

Final Model:
y ~ x1 + x4


  Step Df  Deviance Resid. Df Resid. Dev       AIC
1                          29  1139.1050 111.10402
2 + x1  1 866.49528        28   272.6097  70.20532
3 + x4  1  18.57161        27   254.0381  70.08861</code></pre>
</div>
</div>
<p>Para ver la tabla de resultados del modelo <code>modforw</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modforw)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x1 + x4, data = datos)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.5011 -2.1243 -0.3884  1.9964  6.9582 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  7.179421  18.787955   0.382    0.705    
x1          -0.044479   0.005225  -8.513 3.98e-09 ***
x4           3.077228   2.190294   1.405    0.171    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.067 on 27 degrees of freedom
Multiple R-squared:  0.777, Adjusted R-squared:  0.7605 
F-statistic: 47.03 on 2 and 27 DF,  p-value: 1.594e-09</code></pre>
</div>
</div>
<p>Como la variable <span class="math inline">\(x_4\)</span> no es significativa, entonces se puede <span style="color:red">refinar</span> o actualizar el modelo <code>modforw</code> sacando <span class="math inline">\(x_4\)</span>, esto se puede realizar fácilmente por medio de la función <code>update</code> así:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>modforw <span class="ot">&lt;-</span> <span class="fu">update</span>(modforw, y <span class="sc">~</span> x1)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modforw)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x1, data = datos)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.6063 -2.0276 -0.0457  1.4531  7.0213 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 33.490010   1.535476  21.811  &lt; 2e-16 ***
x1          -0.047026   0.004985  -9.434 3.43e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.12 on 28 degrees of freedom
Multiple R-squared:  0.7607,    Adjusted R-squared:  0.7521 
F-statistic:    89 on 1 and 28 DF,  p-value: 3.429e-10</code></pre>
</div>
</div>
<p>En este <a href="https://www.researchgate.net/post/Why_stepAIC_gives_a_model_with_insignificant_variables_in_the_summarymodel2">enlace</a> usted podrá encontrar la respuesta que le dieron a Audrey al preguntar “Why stepAIC gives a model with insignificant variables?”.</p>
</section>
<section id="aplicación-del-método-both" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="aplicación-del-método-both">Aplicación del método <strong>both</strong></h3>
<p>Para aplicar este método se debe crear un modelo vacío del cual iniciará el proceso. Es necesario definir un punto final de búsqueda, ese punto es una <code>formula</code> que en este caso llamaremos <code>horizonte</code>. A continuación el código.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>modboth <span class="ot">&lt;-</span> <span class="fu">stepAIC</span>(empty.model, <span class="at">trace=</span><span class="cn">FALSE</span>, <span class="at">direction=</span><span class="st">"both"</span>, <span class="at">scope=</span>horizonte)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>modboth<span class="sc">$</span>anova</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Stepwise Model Path 
Analysis of Deviance Table

Initial Model:
y ~ 1

Final Model:
y ~ x1 + x4


  Step Df  Deviance Resid. Df Resid. Dev       AIC
1                          29  1139.1050 111.10402
2 + x1  1 866.49528        28   272.6097  70.20532
3 + x4  1  18.57161        27   254.0381  70.08861</code></pre>
</div>
</div>
<p>El modelo <code>modboth</code> y <code>modforw</code> son el mismo.</p>
<p>A continuación vamos a realizar una comparación de los modelos obtenidos.</p>
<section id="comparando-r2_adj" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="comparando-r2_adj">Comparando <span class="math inline">\(R^2_{Adj}\)</span></h4>
<p>Para extraer el <span class="math inline">\(R^2_{Adj}\)</span> de la tabla de resultados se usa:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modback)<span class="sc">$</span>adj.r.squared</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7808368</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modforw)<span class="sc">$</span>adj.r.squared</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7521337</code></pre>
</div>
</div>
</section>
<section id="comparando-hatsigma" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="comparando-hatsigma">Comparando <span class="math inline">\(\hat{\sigma}\)</span></h4>
<p>Para extraer el <span class="math inline">\(\hat{\sigma}\)</span> de la tabla de resultados se usa:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modback)<span class="sc">$</span>sigma</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.934045</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modforw)<span class="sc">$</span>sigma</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.120266</code></pre>
</div>
</div>
</section>
<section id="comparando-los-residuales" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="comparando-los-residuales">Comparando los residuales</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(modback, <span class="at">main=</span><span class="st">"Backward"</span>, <span class="at">pch=</span><span class="dv">19</span>, <span class="at">cex=</span><span class="dv">1</span>, <span class="at">which=</span><span class="dv">1</span>)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(modforw, <span class="at">main=</span><span class="st">"Forward"</span>, <span class="at">pch=</span><span class="dv">19</span>, <span class="at">cex=</span><span class="dv">1</span>, <span class="at">which=</span><span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="16-selecvar_files/figure-html/selection04-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="ejercicios" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="ejercicios">Ejercicios</h3>
<ol type="1">
<li>¿Qué patrón observa en los gráficos?</li>
<li>Para cada uno de los dos modelos incluya términos cuadráticos con el objetivo de explicar ese patrón cuadrático no explicado y mostrado en los gráficos de residuales anteriores.</li>
</ol>
</section>
</section>
<section id="funciones-addterm-y-dropterm" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="funciones-addterm-y-dropterm">Funciones <code>addterm</code> y <code>dropterm</code></h2>
<p>Estas dos funciones pertenecen al paquete <strong>MASS</strong> <span class="citation" data-cites="R-MASS">(<a href="references.html#ref-R-MASS" role="doc-biblioref">Ripley and Venables 2025</a>)</span> y son útiles para agregar/quitar 1 variable con respecto al modelo ingresado. A continuación la estructura de las funciones.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">addterm</span>(object, ...)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dropterm</span> (object, ...)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="ejemplo-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="ejemplo-1">Ejemplo</h3>
<p>Usando datos anteriores ajuste un modelo para explicar <code>y</code> en función de <code>x2</code> y <code>x5</code>, luego use <code>addterm</code> para determinar cual de las variables <code>x1</code>, <code>x4</code> y <code>x6</code> se debería ingresar.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x2 <span class="sc">+</span> x5, <span class="at">data=</span>datos)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>maximo <span class="ot">&lt;-</span> <span class="fu">formula</span>(<span class="sc">~</span> x1 <span class="sc">+</span> x2 <span class="sc">+</span> x3 <span class="sc">+</span> x4 <span class="sc">+</span> x5 <span class="sc">+</span> x6)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="fu">addterm</span>(mod1, <span class="at">scope=</span>maximo)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Single term additions

Model:
y ~ x2 + x5
       Df Sum of Sq    RSS    AIC
&lt;none&gt;              353.19 79.974
x1      1    88.511 264.67 73.319
x3      1    47.296 305.89 77.661
x4      1    19.915 333.27 80.233
x6      1    19.452 333.73 80.274</code></pre>
</div>
</div>
<p>De la salida anterior se ve que ingresar <code>x1</code> mejoraría el modelo porque lo llevaría de un <span class="math inline">\(AIC=79.974\)</span> a uno con <span class="math inline">\(AIC=73.319\)</span>.</p>
</section>
</section>
<section id="paquete-mixlm" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="paquete-mixlm">Paquete <strong>mixlm</strong></h2>
<p>El paquete <strong>mixlm</strong> creado por <span class="citation" data-cites="R-mixlm">Liland (<a href="references.html#ref-R-mixlm" role="doc-biblioref">2025</a>)</span> contiene un buen número de funciones para modelación. Algunas de las funciones a destacar son <code>forward</code>, <code>backward</code>, <code>stepWise</code>.</p>
<div class="cell" type="rmdwarning">

<div class="rmdwarning">
Este paquete contiene otras funciones <code>lm</code> y <code>glm</code> que se pueden confundir con las funciones <code>lm</code> y <code>glm</code> del paquete <strong>stats</strong>. Por esta razón el usuario debe tener cuidado de usar la apropiada, en estos casos se recomienda usar <code>stats::lm(y ~ x)</code> o <code>mixlm::lm(y ~ x)</code> para obligar a R a que use la que el usuario desea.
</div>
</div>
<section id="ejemplo-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="ejemplo-2">Ejemplo</h3>
<p>En este ejemplo se retoman los datos del ejercicio 9.5 del libro de <a href="https://www.amazon.com/Introduccion-analisis-regresion-lineal-Spanish/dp/9702403278">Montgomery, Peck and Vining (2003)</a>. En este ejemplo se busca encontrar un modelo de regresion lineal que explique la variable respuesta <span class="math inline">\(y\)</span> en función de las covariables <span class="math inline">\(x_1\)</span> a <span class="math inline">\(x_{11}\)</span>, usando el modelo backward y que todas las variables sean significativas a un nivel del 4%.</p>
<p>Para realizar lo solicitado se usa el siguiente código:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MPV) <span class="co"># Aqui estan los datos</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> table.b3[<span class="sc">-</span><span class="fu">c</span>(<span class="dv">23</span>, <span class="dv">25</span>), ] <span class="co"># Eliminando 2 observaciones con NA</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x2 <span class="sc">+</span> x3 <span class="sc">+</span> x4 <span class="sc">+</span> x5 <span class="sc">+</span> x6 <span class="sc">+</span> x7 <span class="sc">+</span> x8 <span class="sc">+</span> x9 <span class="sc">+</span> x10 <span class="sc">+</span> x11,</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">data=</span>datos)</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mixlm)</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a><span class="fu">backward</span>(modelo, <span class="at">alpha=</span><span class="fl">0.04</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Backward elimination, alpha-to-remove: 0.04

Full model: y ~ x1 + x2 + x3 + x4 + x5 + x6 + x7 + x8 + x9 + x10 + x11

    Step    RSS    AIC  R2pred       Cp F value  Pr(&gt;F)  
x11    1 187.87 77.036 0.41925 10.04465  0.0446 0.83503  
x6     2 188.40 75.121 0.51334  8.09610  0.0542 0.81844  
x4     3 191.85 73.666 0.53495  6.42762  0.3664 0.55178  
x2     4 202.63 73.306 0.54991  5.46301  1.1799 0.28968  
x7     5 213.09 72.815 0.61766  4.46743  1.1353 0.29819  
x3     6 217.96 71.494 0.63898  2.93539  0.5259 0.47566  
x1     7 218.73 69.599 0.66089  1.00892  0.0843 0.77406  
x9     8 223.82 68.290 0.73638 -0.50150  0.5826 0.45244  
x5     9 260.14 70.800 0.70705  0.98652  4.2184 0.05017 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x8 + x10, data = datos)

Coefficients:
(Intercept)           x8          x10  
   16.23496      0.21234     -0.01022  </code></pre>
</div>
</div>
<p>De la salida anterior vemos que el modelo final es <code>y ~ x8 + x10</code>. Si comparamos este modelo con el obtenido al usar la función <code>stepAIC</code>, vemos que se eliminó la variable <code>x5</code> ya que su valor-P era 5.02%, superior al límite definido aquí del 4%.</p>
</section>
</section>
<section id="paquete-leaps" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="paquete-leaps">Paquete <strong>leaps</strong></h2>
<p>El paquete <strong>leaps</strong> creado por <span class="citation" data-cites="R-leaps">Fortran code by Alan Miller (<a href="references.html#ref-R-leaps" role="doc-biblioref">2020</a>)</span> está basado en <a href="https://es.wikipedia.org/wiki/Fortran">Fortran</a> y es útil cuando nos interese encontrar subconjuntos de covariables para optimizar las características de un modelo.</p>
<p>La función <code>regsubsets</code> realiza una búsqueda exhaustiva de los mejores subconjuntos de variables <span class="math inline">\(x\)</span> para explicar <span class="math inline">\(y\)</span>. La búsqueda utiliza un algoritmo eficiente de ramificación y unión.</p>
<p>La estructura de la función es la siguiente:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">regsubsets</span>(x, data, nbest, nvmax, ...)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Algunos de los parámetros más usuados en la función son:</p>
<ul>
<li><code>x</code>: fórmula usual.</li>
<li><code>data</code>: marco de datos.</li>
<li><code>nbest</code>: número de subconjuntos de cada tamaño a guardar.</li>
<li><code>nvmax</code>: máximo número de subconjuntos a evaluar.</li>
</ul>
<section id="ejemplo-3" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="ejemplo-3">Ejemplo</h3>
<p>En este ejemplo vamos a usar la base de datos <code>mtcars</code> para encontrar los <strong>dos</strong> mejores modelos con 1, 2, 3 y 4 covariables para explicar <code>mpg</code> en función de las variables <code>disp</code>, <code>hp</code>, <code>wt</code>, <code>qsec</code>.</p>
<p>Para hacer la búsqueda usamos el siguiente código. <code>nbest=2</code> porque queremos los mejores <strong>dos</strong> modelos con cada número de covariables posible.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(leaps)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>model_subset <span class="ot">&lt;-</span> <span class="fu">regsubsets</span>(mpg <span class="sc">~</span> disp <span class="sc">+</span> hp <span class="sc">+</span> wt <span class="sc">+</span> qsec, </span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>                           <span class="at">data=</span>mtcars, <span class="at">nbest=</span><span class="dv">2</span>, <span class="at">nvmax=</span><span class="dv">13</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>El <code>model_subset</code> es un objeto de la clase <code>regsubsets</code> y es posible usar la función S3 <code>summary</code> para objetos de esa clase. A continuación los elementos que componen <code>summary</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(<span class="fu">summary</span>(model_subset))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "which"  "rsq"    "rss"    "adjr2"  "cp"     "bic"    "outmat" "obj"   </code></pre>
</div>
</div>
<p>El primer elemento del <code>summary</code> se obtiene así:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_subset)<span class="sc">$</span>which</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)  disp    hp    wt  qsec
1        TRUE FALSE FALSE  TRUE FALSE
1        TRUE  TRUE FALSE FALSE FALSE
2        TRUE FALSE  TRUE  TRUE FALSE
2        TRUE FALSE FALSE  TRUE  TRUE
3        TRUE FALSE  TRUE  TRUE  TRUE
3        TRUE  TRUE  TRUE  TRUE FALSE
4        TRUE  TRUE  TRUE  TRUE  TRUE</code></pre>
</div>
</div>
<p>De las dos primeras líneas de la salida anterior se observa que los dos mejores modelos con <strong>una</strong> sola covariable son <code>mpg ~ wt</code> y <code>mpg ~ disp</code>. De forma similar, los dos mejores modelos con <strong>dos</strong> covariables son <code>mpg ~ hp + wt</code> y <code>mpg ~ wt + qsec</code>. De forma análoga se interpretan las líneas de la salida anterior.</p>
<p>Es posible mostrar gráficamente los resultados anteriores usando el método S3 <code>plot</code> para objetos de la clase <code>regsubsets</code>. A continuación la estructura de la función <code>plot</code>. El parámetro <code>scale</code> nos permite explorar los mejores modelos para cada uno de los cuatro criterios <span class="math inline">\(BIC\)</span>, <span class="math inline">\(C_p\)</span>, <span class="math inline">\(R^2_{adj}\)</span> y <span class="math inline">\(R^2\)</span>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x, <span class="at">labels=</span>obj<span class="sc">$</span>xnames, <span class="at">main=</span><span class="cn">NULL</span>, </span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">scale=</span><span class="fu">c</span>(<span class="st">"bic"</span>, <span class="st">"Cp"</span>, <span class="st">"adjr2"</span>, <span class="st">"r2"</span>),</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">col=</span><span class="fu">gray</span>(<span class="fu">seq</span>(<span class="dv">0</span>, <span class="fl">0.9</span>, <span class="at">length =</span> <span class="dv">10</span>)),...)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>A continuación el código para mostrar gráficamente los mejores modelos usando el criterio <span class="math inline">\(R^2_{adj}\)</span> y <span class="math inline">\(BIC\)</span>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model_subset, <span class="at">scale=</span><span class="st">"adjr2"</span>, <span class="at">main=</span><span class="fu">expression</span>(R[Adj]<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model_subset, <span class="at">scale=</span><span class="st">"bic"</span>, <span class="at">main=</span><span class="st">"BIC"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="16-selecvar_files/figure-html/selection06-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>De la figura de la izquierda vemos que:</p>
<ul>
<li>El modelo con mayor <span class="math inline">\(R^2_{adj}\)</span> es <code>mpg ~ hp + wt + qsec</code>.</li>
<li>El modelo <code>mpg ~ hp + wt</code> tiene igual <span class="math inline">\(R^2_{adj}\)</span> que <code>mpg ~ wt + qsec</code>.</li>
<li>El mejor modelo con una sola covariable es <code>mpg ~ wt</code>.</li>
</ul>
<p>La figura de la derecha se puede analizar de forma análoga.</p>
<p>Para obtener los valores exacto de <span class="math inline">\(R^2_{adj}\)</span> y <span class="math inline">\(BIC\)</span> mostrados en la figura anterior se usa el siguiente código.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_subset)<span class="sc">$</span>adjr2</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7445939 0.7089548 0.8148396 0.8144448 0.8170643 0.8082829 0.8107212</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_subset)<span class="sc">$</span>bic</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -37.79462 -33.61466 -45.70597 -45.63781 -43.74996 -42.24960 -40.35723</code></pre>
</div>
</div>
<p>Para encontrar el modelo con el mejor <span class="math inline">\(BIC\)</span> se puede usar lo siguiente:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(<span class="fu">summary</span>(model_subset)<span class="sc">$</span>bic <span class="sc">==</span> <span class="fu">min</span>(<span class="fu">summary</span>(model_subset)<span class="sc">$</span>bic))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
</div>
<p>Para determinar la estructura del <span style="color:orange">modelo 3</span> identificado en la salida anterior usamos:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_subset)<span class="sc">$</span>which[<span class="dv">3</span>, ]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)        disp          hp          wt        qsec 
       TRUE       FALSE        TRUE        TRUE       FALSE </code></pre>
</div>
</div>
</section>
</section>
<section id="funciones-para-el-curso-estadística-ii" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="funciones-para-el-curso-estadística-ii">Funciones para el curso Estadística II</h2>
<p>El curso de Estadística II tiene las funciones especiales (<code>myStepwise</code> y <code>myBackward</code>) para realizar la selección de variables como se ha explicado en clase.</p>
<p>La forma de usar las dos funciones para los tres métodos explicados en clase se muestra a continuación.</p>
<ul>
<li>Método forward: <code>myStepwise(full.model=full_mod, alpha.to.enter=alpha, alpha.to.leave=1)</code>.</li>
<li>Método backward: <code>myBackward(base.full=mod, alpha.to.leave=alpha)</code>.</li>
<li>Método both: <code>myStepwise(full.model=mod, alpha.to.enter=alpha, alpha.to.leave=alpha)</code>.</li>
</ul>
<p>El objeto <code>full_mod</code> es el modelo saturado con todas los términos de interés. La cantidad <code>alpha</code> corresponde al nivel de significancia de las pruebas individuales de significancia. Sólo el método forward se fija <code>alpha.to.leave=1</code> para evitar la salida de alguna de las covariables que ingresó.</p>
<div class="cell" type="rmdwarning">

<div class="rmdwarning">
Para el método forward y both se usa la misma función <code>myStepwise</code>. Cuando queremos forward usamos dentro <code>alpha.to.leave=1</code> y cuando queremos both usamos <code>alpha.to.leave=alpha</code>.
</div>
</div>
<p>Para accerder a estas funciones se corre el siguiente código:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"https://raw.githubusercontent.com/fhernanb/Trabajos_Est_2/main/Trabajo%201/funciones.R"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="ejemplo-4" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="ejemplo-4">Ejemplo</h3>
<p>En este ejemplo se busca encontrar un modelo de regresion lineal que explique la variable respuesta <span class="math inline">\(y\)</span> en función de las covariables <span class="math inline">\(x_1\)</span> a <span class="math inline">\(x_{11}\)</span>, los datos provienen del ejercicio 9.5 del libro de <a href="https://www.amazon.com/Introduccion-analisis-regresion-lineal-Spanish/dp/9702403278">Montgomery, Peck and Vining (2003)</a>.</p>
<p>A continuación se muestra el encabezado de la base de datos y la definición de las variables.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/tableb3.PNG" class="img-fluid figure-img" width="786"></p>
<figcaption>Ilustración de la base de datos.</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Nota</strong>: Type of transmission (1=automatic, 0=manual).</p>
<p>Aplique los tres métodos de búsqueda vistos en clase usando <span class="math inline">\(\alpha=0.05\)</span> para las pruebas de hipótesis de individuales de significancia de las variables.</p>
<p><strong>Solución</strong></p>
<p>Antes de iniciar es necesario revisar si hay <code>NA's</code> y eliminarlos.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MPV)  <span class="co"># Aqui estan los datos</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>table.b3[<span class="dv">22</span><span class="sc">:</span><span class="dv">26</span>, ] <span class="co"># Can you see the missing values?</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       y    x1  x2  x3  x4   x5 x6 x7    x8   x9  x10 x11
22 21.47 360.0 180 290 8.4 2.45  2  3 214.2 76.3 4250   1
23 16.59 400.0 185  NA 7.6 3.08  4  3 196.0 73.0 3850   1
24 31.90  96.9  75  83 9.0 4.30  2  5 165.2 61.8 2275   0
25 29.40 140.0  86  NA 8.0 2.92  2  4 176.4 65.4 2150   0
26 13.27 460.0 223 366 8.0 3.00  4  3 228.0 79.8 5430   1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> table.b3[<span class="sc">-</span><span class="fu">c</span>(<span class="dv">23</span>, <span class="dv">25</span>), ]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>El objeto <code>datos</code> tiene la base de datos sin las líneas con <code>NA</code>, lo mismo se hubiese podido realizar usando la función <code>na.omit</code>.</p>
<p>Ahora vamos a ajustar el modelo saturado, es decir, el modelo con todas las covariables.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> ., <span class="at">data=</span>datos)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Para aplicar el método <span style="color:red">Forward</span> visto en clase usamos la siguiente instrucción.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attach</span>(datos)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>mod_forward <span class="ot">&lt;-</span> <span class="fu">myStepwise</span>(<span class="at">full.model=</span>mod, <span class="at">alpha.to.enter=</span><span class="fl">0.05</span>, <span class="at">alpha.to.leave=</span><span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<pre><code>=====
Initial model without covariates

            Estimate Std. Error  t value     Pr(&gt;|t|)
(Intercept) 20.03833   1.144254 17.51214 5.810909e-17

S = 6.267335, R-sq = 0.000000, R-sq(adj) = 0.000000, C-p = 81.412038
=====
+++ Adding x1 

               Estimate  Std. Error   t value     Pr(&gt;|t|)
(Intercept) 33.49000993 1.535476457 21.810826 4.127754e-19
x1          -0.04702616 0.004984804 -9.433904 3.428631e-10

S = 3.120266, R-sq = 0.760681, R-sq(adj) = 0.752134, C-p = 0.184405
=====</code></pre>
<p>Para ver un resumen del modelo resultante con Forward hacemos lo siguiente:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_forward)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<pre><code>Residuals:
    Min      1Q  Median      3Q     Max 
-6.6063 -2.0276 -0.0457  1.4531  7.0213 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 33.490010   1.535476  21.811  &lt; 2e-16 ***
x1          -0.047026   0.004985  -9.434 3.43e-10 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 3.12 on 28 degrees of freedom
Multiple R-squared:  0.7607,    Adjusted R-squared:  0.7521 
F-statistic:    89 on 1 and 28 DF,  p-value: 3.429e-10
</code></pre>
<p>Para aplicar el método <span style="color:red">Backward</span> visto en clase usamos la siguiente instrucción.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>mod_back <span class="ot">&lt;-</span> <span class="fu">myBackward</span>(<span class="at">base.full=</span>mod, <span class="at">alpha.to.leave=</span><span class="fl">0.05</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<pre><code>-------------STEP  1 -------------
 The drop statistics : 
Single term deletions

Model:
y ~ x1 + x2 + x3 + x4 + x5 + x6 + x7 + x8 + x9 + x10 + x11
       Df Sum of Sq    RSS    AIC F value Pr(&gt;F)  
&lt;none&gt;              187.40 78.962                 
x1      1    18.736 206.14 79.820  1.7996 0.1964  
x2      1     6.462 193.86 77.979  0.6207 0.4411  
x3      1    17.770 205.17 79.679  1.7069 0.2078  
x4      1     2.418 189.82 77.346  0.2323 0.6357  
x5      1    35.864 223.26 82.215  3.4447 0.0799 .
x6      1     0.632 188.03 77.063  0.0607 0.8082  
x7      1    11.065 198.47 78.683  1.0628 0.3162  
x8      1    20.047 207.45 80.011  1.9256 0.1822  
x9      1    15.758 203.16 79.384  1.5136 0.2344  
x10     1     7.836 195.24 78.190  0.7526 0.3971  
x11     1     0.465 187.87 77.036  0.0446 0.8350  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

--------
Term dropped in step 1 : x11 
--------

-------------STEP  2 -------------
 The drop statistics : 
Single term deletions

Model:
y ~ x1 + x2 + x3 + x4 + x5 + x6 + x7 + x8 + x9 + x10
       Df Sum of Sq    RSS    AIC F value  Pr(&gt;F)  
&lt;none&gt;              187.87 77.036                  
x1      1    18.280 206.15 77.822  1.8488 0.18985  
x2      1     6.642 194.51 76.078  0.6718 0.42259  
x3      1    17.815 205.68 77.754  1.8018 0.19532  
x4      1     2.363 190.23 75.411  0.2389 0.63057  
x5      1    36.370 224.24 80.345  3.6783 0.07028 .
x6      1     0.536 188.40 75.121  0.0542 0.81844  
x7      1    14.124 201.99 77.211  1.4285 0.24672  
x8      1    20.301 208.17 78.114  2.0531 0.16814  
x9      1    16.914 204.78 77.622  1.7106 0.20652  
x10     1     7.985 195.85 76.285  0.8076 0.38009  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

--------
Term dropped in step 2 : x6 
--------
.
.
.
-------------STEP  10 -------------
 The drop statistics : 
Single term deletions

Model:
y ~ x8 + x10
       Df Sum of Sq    RSS    AIC F value    Pr(&gt;F)    
&lt;none&gt;              260.14 70.800                      
x8      1    50.377 310.52 74.111  5.2286   0.03028 *  
x10     1   233.391 493.53 88.012 24.2239 3.758e-05 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1</code></pre>
<p>Para ver un resumen del modelo resultante de Backward hacemos lo siguiente:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_back)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<pre><code>Residuals:
   Min     1Q Median     3Q    Max 
-4.396 -2.040 -0.691  2.532  6.686 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 16.234963  10.914249   1.488   0.1485    
x8           0.212338   0.092861   2.287   0.0303 *  
x10         -0.010215   0.002075  -4.922 3.76e-05 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 3.104 on 27 degrees of freedom
Multiple R-squared:  0.7716,    Adjusted R-squared:  0.7547 
F-statistic: 45.61 on 2 and 27 DF,  p-value: 2.196e-09</code></pre>
<p>Para aplicar el método de selección <span style="color:red">en ambas direcciones</span> usamos la siguiente instrucción.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>mod_both <span class="ot">&lt;-</span> <span class="fu">myStepwise</span>(<span class="at">full.model=</span>mod, <span class="at">alpha.to.enter=</span><span class="fl">0.05</span>, <span class="at">alpha.to.leave=</span><span class="fl">0.05</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<pre><code>=====
Initial model without covariates

            Estimate Std. Error  t value     Pr(&gt;|t|)
(Intercept) 20.03833   1.144254 17.51214 5.810909e-17

S = 6.267335, R-sq = 0.000000, R-sq(adj) = 0.000000, C-p = 81.412038
=====
+++ Adding x1 

               Estimate  Std. Error   t value     Pr(&gt;|t|)
(Intercept) 33.49000993 1.535476457 21.810826 4.127754e-19
x1          -0.04702616 0.004984804 -9.433904 3.428631e-10

S = 3.120266, R-sq = 0.760681, R-sq(adj) = 0.752134, C-p = 0.184405
=====</code></pre>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-R-leaps" class="csl-entry" role="listitem">
Fortran code by Alan Miller, Thomas Lumley based on. 2020. <em>Leaps: Regression Subset Selection</em>. <a href="https://CRAN.R-project.org/package=leaps">https://CRAN.R-project.org/package=leaps</a>.
</div>
<div id="ref-R-mixlm" class="csl-entry" role="listitem">
Liland, Kristian Hovde. 2025. <em>Mixlm: Mixed Model ANOVA and Statistics for Education</em>. <a href="https://github.com/khliland/mixlm/">https://github.com/khliland/mixlm/</a>.
</div>
<div id="ref-R-MASS" class="csl-entry" role="listitem">
Ripley, Brian, and Bill Venables. 2025. <em>MASS: Support Functions and Datasets for Venables and Ripley’s MASS</em>. <a href="http://www.stats.ox.ac.uk/pub/MASS4/">http://www.stats.ox.ac.uk/pub/MASS4/</a>.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./15-all_possible_reg.html" class="pagination-link" aria-label="Todas las regresiones posibles">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Todas las regresiones posibles</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./17-feature_selection.html" class="pagination-link" aria-label="Feature selection">
        <span class="nav-page-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Feature selection</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>