<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>10 Diagnósticos parte I | Modelos de Regresión con R</title>
  <meta name="description" content="Libro de Modelos de Regresión con R para los estudiantes de la Escuela de Estadística de la Universidad Nacional de Colombia." />
  <meta name="generator" content="bookdown 0.37 and GitBook 2.6.7" />

  <meta property="og:title" content="10 Diagnósticos parte I | Modelos de Regresión con R" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="/images/cover.png" />
  <meta property="og:description" content="Libro de Modelos de Regresión con R para los estudiantes de la Escuela de Estadística de la Universidad Nacional de Colombia." />
  <meta name="github-repo" content="fhernanb/libro_regresion" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="10 Diagnósticos parte I | Modelos de Regresión con R" />
  
  <meta name="twitter:description" content="Libro de Modelos de Regresión con R para los estudiantes de la Escuela de Estadística de la Universidad Nacional de Colombia." />
  <meta name="twitter:image" content="/images/cover.png" />

<meta name="author" content="Freddy Hernández" />
<meta name="author" content="Olga Usuga" />
<meta name="author" content="Mauricio Mazo" />


<meta name="date" content="2024-03-04" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="ph2.html"/>
<link rel="next" href="diag2.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.10.4/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.11.1/plotly-latest.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Modelos de Regresión con R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Bienvenido</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#estructura-del-libro"><i class="fa fa-check"></i>Estructura del libro</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#software-y-convenciones"><i class="fa fa-check"></i>Software y convenciones</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#bloques-informativos"><i class="fa fa-check"></i>Bloques informativos</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="rls.html"><a href="rls.html"><i class="fa fa-check"></i><b>1</b> Regresión lineal simple</a>
<ul>
<li class="chapter" data-level="" data-path="rls.html"><a href="rls.html#modelo-estadístico"><i class="fa fa-check"></i>Modelo estadístico</a></li>
<li class="chapter" data-level="" data-path="rls.html"><a href="rls.html#función-lm"><i class="fa fa-check"></i>Función <code>lm</code></a>
<ul>
<li class="chapter" data-level="" data-path="rls.html"><a href="rls.html#ejemplo"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="rls.html"><a href="rls.html#clase-lm"><i class="fa fa-check"></i>Clase <code>lm</code></a>
<ul>
<li class="chapter" data-level="" data-path="rls.html"><a href="rls.html#ejemplo-1"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="rls.html"><a href="rls.html#mínimos-cuadrados-ponderados"><i class="fa fa-check"></i>Mínimos cuadrados ponderados</a>
<ul>
<li class="chapter" data-level="" data-path="rls.html"><a href="rls.html#ejemplo-2"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="rls.html"><a href="rls.html#apéndice"><i class="fa fa-check"></i>Apéndice</a>
<ul>
<li class="chapter" data-level="" data-path="rls.html"><a href="rls.html#estimación-por-mínimos-cuadrados"><i class="fa fa-check"></i>Estimación por mínimos cuadrados</a></li>
<li class="chapter" data-level="" data-path="rls.html"><a href="rls.html#estimación-por-máxima-verosimilitud"><i class="fa fa-check"></i>Estimación por máxima verosimilitud</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="trans.html"><a href="trans.html"><i class="fa fa-check"></i><b>2</b> Transformaciones</a>
<ul>
<li class="chapter" data-level="" data-path="trans.html"><a href="trans.html#transformaciones-para-linealizar-el-modelo"><i class="fa fa-check"></i>Transformaciones para linealizar el modelo</a>
<ul>
<li class="chapter" data-level="" data-path="trans.html"><a href="trans.html#ejemplo-3"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="rlm.html"><a href="rlm.html"><i class="fa fa-check"></i><b>3</b> Regresión lineal múltiple</a>
<ul>
<li class="chapter" data-level="" data-path="rlm.html"><a href="rlm.html#modelo-estadístico-1"><i class="fa fa-check"></i>Modelo estadístico</a>
<ul>
<li class="chapter" data-level="" data-path="rlm.html"><a href="rlm.html#ejemplo-4"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="predict.html"><a href="predict.html"><i class="fa fa-check"></i><b>4</b> Predicción</a>
<ul>
<li class="chapter" data-level="" data-path="predict.html"><a href="predict.html#función-predict"><i class="fa fa-check"></i>Función <code>predict</code></a>
<ul>
<li class="chapter" data-level="" data-path="predict.html"><a href="predict.html#ejemplo-5"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="predict.html"><a href="predict.html#intervalo-de-confianza-para-la-respuesta-media-eyx_0"><i class="fa fa-check"></i>Intervalo de confianza para la respuesta media <span class="math inline">\(E(Y|x_0)\)</span></a></li>
<li class="chapter" data-level="" data-path="predict.html"><a href="predict.html#intervalo-de-confianza-para-la-predicción-de-nuevas-observaciones"><i class="fa fa-check"></i>Intervalo de confianza para la predicción de nuevas observaciones</a>
<ul>
<li class="chapter" data-level="" data-path="predict.html"><a href="predict.html#ejemplo-6"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="simul.html"><a href="simul.html"><i class="fa fa-check"></i><b>5</b> Simulación</a>
<ul>
<li class="chapter" data-level="" data-path="simul.html"><a href="simul.html#preguntas-sobre-simulación-en-stackoverflow"><i class="fa fa-check"></i>Preguntas sobre simulación en StackOverFlow</a></li>
<li class="chapter" data-level="" data-path="simul.html"><a href="simul.html#simulando-datos-de-un-modelo-lineal"><i class="fa fa-check"></i>Simulando datos de un modelo lineal</a>
<ul>
<li class="chapter" data-level="" data-path="simul.html"><a href="simul.html#ejemplo-7"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="simul.html"><a href="simul.html#función-simulate"><i class="fa fa-check"></i>Función <code>simulate</code></a>
<ul>
<li class="chapter" data-level="" data-path="simul.html"><a href="simul.html#ejemplo-8"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="simul.html"><a href="simul.html#otras-herramientas-para-simular"><i class="fa fa-check"></i>Otras herramientas para simular</a></li>
<li class="chapter" data-level="" data-path="simul.html"><a href="simul.html#videos-sugeridos"><i class="fa fa-check"></i>Videos sugeridos</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="ic.html"><a href="ic.html"><i class="fa fa-check"></i><b>6</b> Intervalos de confianza</a>
<ul>
<li class="chapter" data-level="" data-path="ic.html"><a href="ic.html#función-confint"><i class="fa fa-check"></i>Función <code>confint</code></a>
<ul>
<li class="chapter" data-level="" data-path="ic.html"><a href="ic.html#ejemplo-9"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="ic.html"><a href="ic.html#función-confint_sigma2"><i class="fa fa-check"></i>Función <code>confint_sigma2</code></a>
<ul>
<li class="chapter" data-level="" data-path="ic.html"><a href="ic.html#ejemplo-10"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="varcuali.html"><a href="varcuali.html"><i class="fa fa-check"></i><b>7</b> Modelos con variables cualitativas</a>
<ul>
<li class="chapter" data-level="" data-path="varcuali.html"><a href="varcuali.html#es-posible-incluir-variables-cualitativas"><i class="fa fa-check"></i>¿Es posible incluir variables cualitativas?</a></li>
<li class="chapter" data-level="" data-path="varcuali.html"><a href="varcuali.html#variable-indicadora-dummy-ficticia-o-binaria"><i class="fa fa-check"></i>Variable indicadora, dummy, ficticia o binaria</a></li>
<li class="chapter" data-level="" data-path="varcuali.html"><a href="varcuali.html#creando-variables-indicadoras"><i class="fa fa-check"></i>Creando variables indicadoras</a>
<ul>
<li class="chapter" data-level="" data-path="varcuali.html"><a href="varcuali.html#ejemplo-11"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="varcuali.html"><a href="varcuali.html#modelos-con-variables-cualitativas"><i class="fa fa-check"></i>Modelos con variables cualitativas</a>
<ul>
<li class="chapter" data-level="" data-path="varcuali.html"><a href="varcuali.html#ejemplo-12"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="varcuali.html"><a href="varcuali.html#significancia-de-variables-cualitativas"><i class="fa fa-check"></i>Significancia de variables cualitativas</a>
<ul>
<li class="chapter" data-level="" data-path="varcuali.html"><a href="varcuali.html#ejemplo-13"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="varcuali.html"><a href="varcuali.html#ejemplo-14"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="ph1.html"><a href="ph1.html"><i class="fa fa-check"></i><b>8</b> Pruebas de hipótesis parte I</a>
<ul>
<li class="chapter" data-level="" data-path="ph1.html"><a href="ph1.html#pruebas-sobre-los-coeficientes-beta"><i class="fa fa-check"></i>Pruebas sobre los coeficientes <span class="math inline">\(\beta\)</span></a></li>
<li class="chapter" data-level="" data-path="ph1.html"><a href="ph1.html#función-summary-cuando-beta_j0-0"><i class="fa fa-check"></i>Función <code>summary</code> cuando <span class="math inline">\(\beta_{j0} = 0\)</span></a>
<ul>
<li class="chapter" data-level="" data-path="ph1.html"><a href="ph1.html#ejemplo-15"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="ph1.html"><a href="ph1.html#función-beta_test-cuando-beta_k0-neq-0"><i class="fa fa-check"></i>Función <code>beta_test</code> cuando <span class="math inline">\(\beta_{k0} \neq 0\)</span></a>
<ul>
<li class="chapter" data-level="" data-path="ph1.html"><a href="ph1.html#ejemplo-16"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="ph2.html"><a href="ph2.html"><i class="fa fa-check"></i><b>9</b> Pruebas de hipótesis parte II</a>
<ul>
<li class="chapter" data-level="" data-path="ph2.html"><a href="ph2.html#prueba-sobre-todos-los-coeficientes"><i class="fa fa-check"></i>Prueba sobre todos los coeficientes</a>
<ul>
<li class="chapter" data-level="" data-path="ph2.html"><a href="ph2.html#ejemplo-17"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="ph2.html"><a href="ph2.html#ejemplo-18"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="ph2.html"><a href="ph2.html#prueba-para-comparar-modelos-anidados"><i class="fa fa-check"></i>Prueba para comparar modelos anidados</a>
<ul>
<li class="chapter" data-level="" data-path="ph2.html"><a href="ph2.html#ejemplo-19"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="ph2.html"><a href="ph2.html#función-anova"><i class="fa fa-check"></i>Función <code>anova</code></a>
<ul>
<li class="chapter" data-level="" data-path="ph2.html"><a href="ph2.html#ejemplo-20"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="ph2.html"><a href="ph2.html#ejemplo-21"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="ph2.html"><a href="ph2.html#summary-versus-anova"><i class="fa fa-check"></i><code>summary</code> versus <code>anova</code></a>
<ul>
<li class="chapter" data-level="" data-path="ph2.html"><a href="ph2.html#ejemplo-22"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="ph2.html"><a href="ph2.html#prueba-razón-de-verosimilitud"><i class="fa fa-check"></i>Prueba razón de verosimilitud</a>
<ul>
<li class="chapter" data-level="" data-path="ph2.html"><a href="ph2.html#ejemplo-23"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="ph2.html"><a href="ph2.html#comparaciones-múltiples"><i class="fa fa-check"></i>Comparaciones múltiples</a>
<ul>
<li class="chapter" data-level="" data-path="ph2.html"><a href="ph2.html#ejemplo-24"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="diag1.html"><a href="diag1.html"><i class="fa fa-check"></i><b>10</b> Diagnósticos parte I</a>
<ul>
<li class="chapter" data-level="" data-path="diag1.html"><a href="diag1.html#supuestos"><i class="fa fa-check"></i>Supuestos</a></li>
<li class="chapter" data-level="" data-path="diag1.html"><a href="diag1.html#residuales"><i class="fa fa-check"></i>Residuales</a>
<ul>
<li class="chapter" data-level="" data-path="diag1.html"><a href="diag1.html#ejemplo-25"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="diag1.html"><a href="diag1.html#chequeando-normalidad-de-los-errores"><i class="fa fa-check"></i>Chequeando normalidad de los errores</a></li>
<li class="chapter" data-level="" data-path="diag1.html"><a href="diag1.html#chequeando-si-errores-con-media-cero"><i class="fa fa-check"></i>Chequeando si errores con media cero</a></li>
<li class="chapter" data-level="" data-path="diag1.html"><a href="diag1.html#chequeando-si-los-errores-tiene-varianza-constante"><i class="fa fa-check"></i>Chequeando si los errores tiene varianza constante</a></li>
<li class="chapter" data-level="" data-path="diag1.html"><a href="diag1.html#chequeando-si-errores-no-están-correlacionados"><i class="fa fa-check"></i>Chequeando si errores no están correlacionados</a>
<ul>
<li class="chapter" data-level="" data-path="diag1.html"><a href="diag1.html#ejemplo-cumpliendo-los-supuestos"><i class="fa fa-check"></i>Ejemplo cumpliendo los supuestos</a></li>
<li class="chapter" data-level="" data-path="diag1.html"><a href="diag1.html#ejemplo-violando-los-supuestos"><i class="fa fa-check"></i>Ejemplo violando los supuestos</a></li>
<li class="chapter" data-level="" data-path="diag1.html"><a href="diag1.html#ejemplo-violando-los-supuestos-1"><i class="fa fa-check"></i>Ejemplo violando los supuestos</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="diag1.html"><a href="diag1.html#gráficos-de-residuales-usando-car"><i class="fa fa-check"></i>Gráficos de residuales usando car</a>
<ul>
<li class="chapter" data-level="" data-path="diag1.html"><a href="diag1.html#ejemplo-26"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="diag1.html"><a href="diag1.html#prueba-de-falta-de-ajuste"><i class="fa fa-check"></i>Prueba de falta de ajuste</a>
<ul>
<li class="chapter" data-level="" data-path="diag1.html"><a href="diag1.html#ejemplo-1-1"><i class="fa fa-check"></i>Ejemplo 1</a></li>
<li class="chapter" data-level="" data-path="diag1.html"><a href="diag1.html#ejemplo-2-1"><i class="fa fa-check"></i>Ejemplo 2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="diag2.html"><a href="diag2.html"><i class="fa fa-check"></i><b>11</b> Diagnósticos parte II</a>
<ul>
<li class="chapter" data-level="" data-path="diag2.html"><a href="diag2.html#matriz-sombrero-o-hat"><i class="fa fa-check"></i>Matriz sombrero o hat</a></li>
<li class="chapter" data-level="" data-path="diag2.html"><a href="diag2.html#qué-es-extrapolación-oculta"><i class="fa fa-check"></i>¿Qué es extrapolación oculta?</a>
<ul>
<li class="chapter" data-level="" data-path="diag2.html"><a href="diag2.html#ejemplo-27"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="diag2.html"><a href="diag2.html#reto-para-el-lector"><i class="fa fa-check"></i>Reto para el lector</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="diag2.html"><a href="diag2.html#punto-atípico-outlier-y-punto-influyente"><i class="fa fa-check"></i>Punto atípico (outlier) y punto influyente</a></li>
<li class="chapter" data-level="" data-path="diag2.html"><a href="diag2.html#prueba-de-bonferroni-para-detectar-outliers"><i class="fa fa-check"></i>Prueba de Bonferroni para detectar outliers</a>
<ul>
<li class="chapter" data-level="" data-path="diag2.html"><a href="diag2.html#ejemplo-28"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="diag2.html"><a href="diag2.html#distancia-de-cook"><i class="fa fa-check"></i>Distancia de Cook</a>
<ul>
<li class="chapter" data-level="" data-path="diag2.html"><a href="diag2.html#ejemplo-29"><i class="fa fa-check"></i>Ejemplo:</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="diag2.html"><a href="diag2.html#dffits"><i class="fa fa-check"></i>DFFITS</a></li>
<li class="chapter" data-level="" data-path="diag2.html"><a href="diag2.html#dfbetas"><i class="fa fa-check"></i>DFBETAS</a>
<ul>
<li class="chapter" data-level="" data-path="diag2.html"><a href="diag2.html#ejemplo-30"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="diag2.html"><a href="diag2.html#estadística-press-y-r2-de-predicción"><i class="fa fa-check"></i>Estadística PRESS y <span class="math inline">\(R^2\)</span> de predicción</a>
<ul>
<li class="chapter" data-level="" data-path="diag2.html"><a href="diag2.html#ejemplo-31"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="diag2.html"><a href="diag2.html#valores-de-corte-para-diagnósticos"><i class="fa fa-check"></i>Valores de corte para diagnósticos</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="homo.html"><a href="homo.html"><i class="fa fa-check"></i><b>12</b> Pruebas de Homocedasticidad</a>
<ul>
<li class="chapter" data-level="" data-path="homo.html"><a href="homo.html#breusch-pagan-test"><i class="fa fa-check"></i>Breusch-Pagan Test</a>
<ul>
<li class="chapter" data-level="" data-path="homo.html"><a href="homo.html#ejemplo-32"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="homo.html"><a href="homo.html#white-test"><i class="fa fa-check"></i>White test</a>
<ul>
<li class="chapter" data-level="" data-path="homo.html"><a href="homo.html#ejemplo-33"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="homo.html"><a href="homo.html#score-test-for-nonconstant-error-variance"><i class="fa fa-check"></i>Score test for nonconstant error variance</a>
<ul>
<li class="chapter" data-level="" data-path="homo.html"><a href="homo.html#ejemplo-34"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="homo.html"><a href="homo.html#goldfeld-quandt-test"><i class="fa fa-check"></i>Goldfeld-Quandt Test</a></li>
<li class="chapter" data-level="" data-path="homo.html"><a href="homo.html#harrison-mccabe-test"><i class="fa fa-check"></i>Harrison-McCabe test</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="indep.html"><a href="indep.html"><i class="fa fa-check"></i><b>13</b> Pruebas de independencia de los errores</a>
<ul>
<li class="chapter" data-level="" data-path="indep.html"><a href="indep.html#durbin-watson-test"><i class="fa fa-check"></i>Durbin-Watson test</a>
<ul>
<li class="chapter" data-level="" data-path="indep.html"><a href="indep.html#ejemplo-35"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="indep.html"><a href="indep.html#breusch-godfrey-test"><i class="fa fa-check"></i>Breusch-Godfrey Test</a>
<ul>
<li class="chapter" data-level="" data-path="indep.html"><a href="indep.html#ejemplo-36"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="mod_poli.html"><a href="mod_poli.html"><i class="fa fa-check"></i><b>14</b> Modelos polinomiales</a>
<ul>
<li class="chapter" data-level="" data-path="mod_poli.html"><a href="mod_poli.html#modelos-polinomiales-de-una-o-varias-variables"><i class="fa fa-check"></i>Modelos polinomiales de una o varias variables</a></li>
<li class="chapter" data-level="" data-path="mod_poli.html"><a href="mod_poli.html#funciones-i-y-poly"><i class="fa fa-check"></i>Funciones <code>I()</code> y <code>poly()</code></a></li>
<li class="chapter" data-level="" data-path="mod_poli.html"><a href="mod_poli.html#modelos-polinomiales-con-splines"><i class="fa fa-check"></i>Modelos polinomiales con splines</a>
<ul>
<li class="chapter" data-level="" data-path="mod_poli.html"><a href="mod_poli.html#ejemplo-38"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="mod_poli.html"><a href="mod_poli.html#función-bs"><i class="fa fa-check"></i>Función <code>bs</code></a>
<ul>
<li class="chapter" data-level="" data-path="mod_poli.html"><a href="mod_poli.html#ejemplo-39"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="mod_poli.html"><a href="mod_poli.html#ejemplo-40"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="mod_poli.html"><a href="mod_poli.html#función-lowess"><i class="fa fa-check"></i>Función <code>lowess</code></a>
<ul>
<li class="chapter" data-level="" data-path="mod_poli.html"><a href="mod_poli.html#ejemplo-41"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="mod_poli.html"><a href="mod_poli.html#función-loess"><i class="fa fa-check"></i>Función <code>loess</code></a>
<ul>
<li class="chapter" data-level="" data-path="mod_poli.html"><a href="mod_poli.html#ejemplo-42"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="mod_poli.html"><a href="mod_poli.html#optimización-con-superficies-de-respuesta"><i class="fa fa-check"></i>Optimización con superficies de respuesta</a>
<ul>
<li class="chapter" data-level="" data-path="mod_poli.html"><a href="mod_poli.html#función-nlminb"><i class="fa fa-check"></i>Función <code>nlminb</code></a></li>
<li class="chapter" data-level="" data-path="mod_poli.html"><a href="mod_poli.html#ejemplo-43"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="mod_poli.html"><a href="mod_poli.html#polinomios-ortogonales"><i class="fa fa-check"></i>Polinomios ortogonales</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="selec.html"><a href="selec.html"><i class="fa fa-check"></i><b>15</b> Selección de variables</a>
<ul>
<li class="chapter" data-level="" data-path="selec.html"><a href="selec.html#akaike-information-criterion-aic"><i class="fa fa-check"></i>Akaike Information Criterion (<span class="math inline">\(AIC\)</span>)</a></li>
<li class="chapter" data-level="" data-path="selec.html"><a href="selec.html#funciones-loglik-y-aic"><i class="fa fa-check"></i>Funciones <code>logLik</code> y <code>AIC</code></a></li>
<li class="chapter" data-level="" data-path="selec.html"><a href="selec.html#métodos"><i class="fa fa-check"></i>Métodos</a></li>
<li class="chapter" data-level="" data-path="selec.html"><a href="selec.html#función-stepaic"><i class="fa fa-check"></i>Función <code>stepAIC</code></a>
<ul>
<li class="chapter" data-level="" data-path="selec.html"><a href="selec.html#ejemplo-44"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="selec.html"><a href="selec.html#aplicación-del-método-backward"><i class="fa fa-check"></i>Aplicación del método <strong>backward</strong></a></li>
<li class="chapter" data-level="" data-path="selec.html"><a href="selec.html#aplicación-del-método-forward"><i class="fa fa-check"></i>Aplicación del método <strong>forward</strong></a></li>
<li class="chapter" data-level="" data-path="selec.html"><a href="selec.html#aplicación-del-método-both"><i class="fa fa-check"></i>Aplicación del método <strong>both</strong></a></li>
<li class="chapter" data-level="" data-path="selec.html"><a href="selec.html#ejercicios"><i class="fa fa-check"></i>Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="selec.html"><a href="selec.html#funciones-addterm-y-dropterm"><i class="fa fa-check"></i>Funciones <code>addterm</code> y <code>dropterm</code></a>
<ul>
<li class="chapter" data-level="" data-path="selec.html"><a href="selec.html#ejemplo-45"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="selec.html"><a href="selec.html#paquete-olsrr"><i class="fa fa-check"></i>Paquete <strong>olsrr</strong></a>
<ul>
<li class="chapter" data-level="" data-path="selec.html"><a href="selec.html#ejemplo-46"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="selec.html"><a href="selec.html#paquete-mixlm"><i class="fa fa-check"></i>Paquete <strong>mixlm</strong></a>
<ul>
<li class="chapter" data-level="" data-path="selec.html"><a href="selec.html#ejemplo-47"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="selec.html"><a href="selec.html#paquete-leaps"><i class="fa fa-check"></i>Paquete <strong>leaps</strong></a>
<ul>
<li class="chapter" data-level="" data-path="selec.html"><a href="selec.html#ejemplo-48"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="feature_selec.html"><a href="feature_selec.html"><i class="fa fa-check"></i><b>16</b> Feature selection</a>
<ul>
<li class="chapter" data-level="" data-path="feature_selec.html"><a href="feature_selec.html#feature-selection-with-the-caret-r-package"><i class="fa fa-check"></i>Feature Selection with the Caret R Package</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="multicoli.html"><a href="multicoli.html"><i class="fa fa-check"></i><b>17</b> Multicolinealidad</a>
<ul>
<li class="chapter" data-level="" data-path="multicoli.html"><a href="multicoli.html#qué-es-multicolinealidad"><i class="fa fa-check"></i>¿Qué es multicolinealidad?</a></li>
<li class="chapter" data-level="" data-path="multicoli.html"><a href="multicoli.html#multicolinealidad-inducida"><i class="fa fa-check"></i>Multicolinealidad inducida</a></li>
<li class="chapter" data-level="" data-path="multicoli.html"><a href="multicoli.html#cómo-identificar-la-multicolinealidad"><i class="fa fa-check"></i>¿Cómo identificar la multicolinealidad?</a></li>
<li class="chapter" data-level="" data-path="multicoli.html"><a href="multicoli.html#matriz-de-correlaciones"><i class="fa fa-check"></i>Matriz de correlaciones</a>
<ul>
<li class="chapter" data-level="" data-path="multicoli.html"><a href="multicoli.html#ejemplo-49"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="multicoli.html"><a href="multicoli.html#factor-de-inflación-de-la-varianza-vif"><i class="fa fa-check"></i>Factor de Inflación de la Varianza (VIF)</a>
<ul>
<li class="chapter" data-level="" data-path="multicoli.html"><a href="multicoli.html#ejemplo-50"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="18" data-path="algmat.html"><a href="algmat.html"><i class="fa fa-check"></i><b>18</b> Algebra matricial con R</a>
<ul>
<li class="chapter" data-level="" data-path="algmat.html"><a href="algmat.html#matrices"><i class="fa fa-check"></i>Matrices</a>
<ul>
<li class="chapter" data-level="" data-path="algmat.html"><a href="algmat.html#ejemplo-51"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="algmat.html"><a href="algmat.html#operaciones-básicas-sobre-una-matriz"><i class="fa fa-check"></i>Operaciones básicas sobre una matriz</a></li>
<li class="chapter" data-level="" data-path="algmat.html"><a href="algmat.html#rango-de-una-matriz"><i class="fa fa-check"></i>Rango de una matriz</a>
<ul>
<li class="chapter" data-level="" data-path="algmat.html"><a href="algmat.html#ejemplo-52"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="algmat.html"><a href="algmat.html#ejemplo-53"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="19" data-path="WilRog.html"><a href="WilRog.html"><i class="fa fa-check"></i><b>19</b> Notación de Wilkinson y Rogers</a>
<ul>
<li class="chapter" data-level="" data-path="WilRog.html"><a href="WilRog.html#qué-es-una-fórmula-en-r"><i class="fa fa-check"></i>¿Qué es una fórmula en R?</a></li>
<li class="chapter" data-level="" data-path="WilRog.html"><a href="WilRog.html#para-qué-sirve-la-notación-de-wilkinson-y-rogers"><i class="fa fa-check"></i>¿Para qué sirve la notación de Wilkinson y Rogers?</a></li>
<li class="chapter" data-level="" data-path="WilRog.html"><a href="WilRog.html#paquete-formula-de-r"><i class="fa fa-check"></i>Paquete Formula de R</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="xy.html"><a href="xy.html"><i class="fa fa-check"></i><b>20</b> ¿Cómo obtener la matriz <span class="math inline">\(\boldsymbol{X}\)</span> y el vector <span class="math inline">\(\boldsymbol{y}\)</span>?</a>
<ul>
<li class="chapter" data-level="" data-path="xy.html"><a href="xy.html#ejemplo-54"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="important.html"><a href="important.html"><i class="fa fa-check"></i><b>21</b> Otros aspectos importantes</a>
<ul>
<li class="chapter" data-level="" data-path="important.html"><a href="important.html#qué-otras-funciones-hay-en-r-para-ajustar-un-modelo"><i class="fa fa-check"></i>¿Qué otras funciones hay en R para ajustar un modelo?</a>
<ul>
<li class="chapter" data-level="" data-path="important.html"><a href="important.html#ejemplo-55"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="important.html"><a href="important.html#modelos-de-regresión-con-grandes-conjuntos-de-datos"><i class="fa fa-check"></i>Modelos de regresión con grandes conjuntos de datos</a></li>
<li class="chapter" data-level="" data-path="important.html"><a href="important.html#fast-lm-in-r"><i class="fa fa-check"></i>Fast <code>lm</code> in R</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="pasos.html"><a href="pasos.html"><i class="fa fa-check"></i><b>22</b> Pasos para construir modelos</a>
<ul>
<li class="chapter" data-level="" data-path="pasos.html"><a href="pasos.html#pasos-para-construir-un-modelo"><i class="fa fa-check"></i>Pasos para construir UN modelo</a></li>
<li class="chapter" data-level="" data-path="pasos.html"><a href="pasos.html#pasos-para-comparar-varios-modelos"><i class="fa fa-check"></i>Pasos para comparar varios modelos</a></li>
</ul></li>
<li class="chapter" data-level="23" data-path="misspecification.html"><a href="misspecification.html"><i class="fa fa-check"></i><b>23</b> Mala especificación</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Modelos de Regresión con R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="diag1" class="section level1 hasAnchor" number="10">
<h1><span class="header-section-number">10</span> Diagnósticos parte I<a href="diag1.html#diag1" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>En este capítulo se presentan varias herramientas útiles para hacer diagnósticos de un modelo ajustado.</p>
<div id="supuestos" class="section level2 unnumbered hasAnchor">
<h2>Supuestos<a href="diag1.html#supuestos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Los supuestos en un modelo de regresión se pueden escribir de dos formas:</p>
<p><strong>Forma I</strong></p>
<ol style="list-style-type: decimal">
<li>Los errores <span class="math inline">\(\epsilon_i\)</span> tienen distribución normal.</li>
<li>Los errores <span class="math inline">\(\epsilon_i\)</span> tienen media cero.</li>
<li>Los errores <span class="math inline">\(\epsilon_i\)</span> tiene varianza constante.</li>
<li>Los errores <span class="math inline">\(\epsilon_i\)</span> no están correlacionados.</li>
</ol>
<p><strong>Forma II</strong></p>
<ol style="list-style-type: decimal">
<li>La respuesta <span class="math inline">\(y\)</span> tiene distribución normal.</li>
<li>La varianza de la respuesta <span class="math inline">\(y\)</span> es constante.</li>
<li>Las observaciones son independientes <span class="math inline">\(y\)</span>.</li>
<li>Relación lineal entre la variable respuesta y las covariables.</li>
</ol>
<p>Ambos conjuntos de supuestos son equivalentes, la forma I está dirigida hacia los errores mientras que en la forma II está dirigida hacia los <span class="math inline">\(y_i\)</span>.</p>
</div>
<div id="residuales" class="section level2 unnumbered hasAnchor">
<h2>Residuales<a href="diag1.html#residuales" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Los residuales en los modelos de regresión nos ayuda a:</p>
<ul>
<li>determinar qué tan bien el modelo explica el patrón de los datos,</li>
<li>verificar el cumplimiento de los supuestos del modelo.</li>
</ul>
<p align="center">
<img src="images/ResidualsLinear.gif" width="200">
</p>
<p>A continuación se muestran los diferentes tipos de residuales que se pueden definir para un modelo de regresión.</p>
<p align="center">
<img src="images/tipos_de_residuales.png" width="600">
</p>
<p>La cantidad <span class="math inline">\(w_i\)</span> corresponde al peso o importancia de cada observación en el modelo, por defecto es <span class="math inline">\(w_i=1\)</span>.</p>
<p>La cantidad <span class="math inline">\(h_{ii}\)</span> se llama leverage y corresponde al elemento <span class="math inline">\(i\)</span> de la diagonal de la matriz sombrero o hat <span class="math inline">\(\boldsymbol{H} = \boldsymbol{X}(\boldsymbol{X}^\top \boldsymbol{X})^{-1}\boldsymbol{X}^\top\)</span>.</p>
<p>La varianza <span class="math inline">\(\hat{\sigma}_{(i)}^{2}\)</span> es la varianza estimada al <strong>NO</strong> tener en cuenta la observación <span class="math inline">\(i\)</span>-ésima. La cantidad <span class="math inline">\(\hat{y}_{(i)}\)</span> es la estimación de la <span class="math inline">\(i\)</span>-ésima observación usando un modelo en el cual la observación <span class="math inline">\(i\)</span>-ésima <strong>NO</strong> fue usada en el ajuste del modelo.</p>
<p>Para obtener los residuales arriba definidos tenemos las siguientes funciones:</p>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="diag1.html#cb171-1" tabindex="-1"></a><span class="fu">residuals</span>(object, <span class="at">type=</span><span class="fu">c</span>(<span class="st">&quot;working&quot;</span>, <span class="st">&quot;response&quot;</span>, <span class="st">&quot;deviance&quot;</span>, <span class="st">&quot;pearson&quot;</span>, <span class="st">&quot;partial&quot;</span>))</span>
<span id="cb171-2"><a href="diag1.html#cb171-2" tabindex="-1"></a><span class="fu">rstandard</span>(object)</span>
<span id="cb171-3"><a href="diag1.html#cb171-3" tabindex="-1"></a><span class="fu">rstudent</span>(object)</span></code></pre></div>
<p>Si un modelo lineal está correctamente especificado (ajustado), los residuos de Pearson serán independientes de los valores ajustados e independientes de los predictores, y estos gráficos deben ser “gráficos nulos”, es decir, gráficos sin características sistemáticas, en el sentido de que la distribución condicional de los residuos (en el eje vertical del gráfico) no debe cambiar con los valores ajustados o con un predictor (en el eje horizontal) <span class="citation">(<a href="#ref-fox2019">J. Fox and Weisberg 2019</a>)</span>.</p>

<div class="rmdwarning">
Los errores del modelo se denotan como <span class="math inline">\(\epsilon_i\)</span> mientras que los residuales usuales se denotan como <span class="math inline">\(e_i\)</span>, no los confunda.
</div>
<div id="ejemplo-25" class="section level3 unnumbered hasAnchor">
<h3>Ejemplo<a href="diag1.html#ejemplo-25" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Considere los datos mostrados abajo, ajuste un modelo de regresión lineal para explicar la media de <span class="math inline">\(y\)</span> en función de <span class="math inline">\(x\)</span> y usando como pesos los valores de <span class="math inline">\(w\)</span>. Obtenga los residuales usando las definiciones y luego usando las funciones de R, compruebe que los resultados coinciden.</p>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="diag1.html#cb172-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">8</span>, <span class="dv">7</span>, <span class="dv">8</span>, <span class="dv">5</span>)</span>
<span id="cb172-2"><a href="diag1.html#cb172-2" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">4</span>)</span>
<span id="cb172-3"><a href="diag1.html#cb172-3" tabindex="-1"></a>w <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.1</span>, <span class="fl">0.1</span>, <span class="fl">0.2</span>, <span class="fl">0.1</span>, <span class="fl">0.2</span>, <span class="fl">0.9</span>)</span></code></pre></div>
<p><strong>Solución</strong></p>
<p>Primero se van a calcular los residuales manualmente aplicando las definiciones.</p>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb173-1"><a href="diag1.html#cb173-1" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x, <span class="at">weights=</span>w)</span>
<span id="cb173-2"><a href="diag1.html#cb173-2" tabindex="-1"></a></span>
<span id="cb173-3"><a href="diag1.html#cb173-3" tabindex="-1"></a>ei <span class="ot">&lt;-</span> y <span class="sc">-</span> <span class="fu">fitted</span>(mod)</span>
<span id="cb173-4"><a href="diag1.html#cb173-4" tabindex="-1"></a>pi <span class="ot">&lt;-</span> ei <span class="sc">*</span> <span class="fu">sqrt</span>(mod<span class="sc">$</span>weights)</span>
<span id="cb173-5"><a href="diag1.html#cb173-5" tabindex="-1"></a>hii <span class="ot">&lt;-</span> <span class="fu">lm.influence</span>(mod)<span class="sc">$</span>hat</span>
<span id="cb173-6"><a href="diag1.html#cb173-6" tabindex="-1"></a>di <span class="ot">&lt;-</span> ei <span class="sc">*</span> <span class="fu">sqrt</span>(mod<span class="sc">$</span>weights) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">summary</span>(mod)<span class="sc">$</span>sigma<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> (<span class="dv">1</span><span class="sc">-</span>hii))</span>
<span id="cb173-7"><a href="diag1.html#cb173-7" tabindex="-1"></a>ri <span class="ot">&lt;-</span> ei <span class="sc">*</span> <span class="fu">sqrt</span>(mod<span class="sc">$</span>weights) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">lm.influence</span>(mod)<span class="sc">$</span>sigma<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> (<span class="dv">1</span><span class="sc">-</span>hii))</span>
<span id="cb173-8"><a href="diag1.html#cb173-8" tabindex="-1"></a></span>
<span id="cb173-9"><a href="diag1.html#cb173-9" tabindex="-1"></a><span class="fu">cbind</span>(<span class="at">ei=</span>ei, <span class="at">pi=</span>pi, <span class="at">di=</span>di, <span class="at">ri=</span>ri)</span></code></pre></div>
<pre><code>##           ei          pi          di          ri
## 1 -2.3487395 -0.74273664 -1.36444485 -1.61615603
## 2 -1.7100840 -0.54077605 -0.92897379 -0.90846102
## 3 -1.0714286 -0.47915742 -1.05401601 -1.07406432
## 4  0.1092437  0.03454589  0.06072186  0.05261092
## 5  0.9285714  0.41526977  0.91348054  0.88927302
## 6  0.4705882  0.44643920  1.63607317  2.46342873</code></pre>
<p>Ahora se van a calcular los residuales usando las funciones de R.</p>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb175-1"><a href="diag1.html#cb175-1" tabindex="-1"></a><span class="fu">cbind</span>(<span class="at">ei=</span><span class="fu">residuals</span>(mod, <span class="at">type=</span><span class="st">&#39;working&#39;</span>),</span>
<span id="cb175-2"><a href="diag1.html#cb175-2" tabindex="-1"></a>      <span class="at">pi=</span><span class="fu">residuals</span>(mod, <span class="at">type=</span><span class="st">&#39;pearson&#39;</span>),</span>
<span id="cb175-3"><a href="diag1.html#cb175-3" tabindex="-1"></a>      <span class="at">di=</span><span class="fu">rstandard</span>(mod),</span>
<span id="cb175-4"><a href="diag1.html#cb175-4" tabindex="-1"></a>      <span class="at">ri=</span><span class="fu">rstudent</span>(mod))</span></code></pre></div>
<pre><code>##           ei          pi          di          ri
## 1 -2.3487395 -0.74273664 -1.36444485 -1.61615603
## 2 -1.7100840 -0.54077605 -0.92897379 -0.90846102
## 3 -1.0714286 -0.47915742 -1.05401601 -1.07406432
## 4  0.1092437  0.03454589  0.06072186  0.05261092
## 5  0.9285714  0.41526977  0.91348054  0.88927302
## 6  0.4705882  0.44643920  1.63607317  2.46342873</code></pre>
<p>Estimado lector, <strong>¿qué puede usted concluir de los resultados de este ejemplo?</strong></p>
</div>
</div>
<div id="chequeando-normalidad-de-los-errores" class="section level2 unnumbered hasAnchor">
<h2>Chequeando normalidad de los errores<a href="diag1.html#chequeando-normalidad-de-los-errores" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Para estudiar si lo errores tienen una distribución aproximadamente normal se construyen los residuales estandarizados <span class="math inline">\(d_i\)</span>. Una vez calculados los <span class="math inline">\(d_i\)</span> se construye un gráfico de normalidad o qqplot usando la función <code>qqnorm</code>, el resultado es un gráfico similar al mostrado a continuación.</p>
<p align="center">
<img src="images/qq_residuales_estandarizados.png" width="450">
</p>
<p>En la siguiente figura se muestran los diferentes patrones que se pueden encontrar en el gráfico de normalidad para <span class="math inline">\(d_i\)</span>. Para que se cumpla el supuesto de normalidad de los errores <span class="math inline">\(e_i\)</span> se necesita que los <span class="math inline">\(d_i\)</span> estén lo más alineados con la recta de referencia, alejamientos severos de esta recta significa que se viola el supuesto de normalidad de los errores.</p>
<p align="center">
<img src="images/patrones_qqplot.png" width="450">
</p>
</div>
<div id="chequeando-si-errores-con-media-cero" class="section level2 unnumbered hasAnchor">
<h2>Chequeando si errores con media cero<a href="diag1.html#chequeando-si-errores-con-media-cero" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Para determinar si los errores tienen una media cerca al valor de cero se puede usar la función <code>mean</code> sobre los residuales <span class="math inline">\(e_i\)</span>.</p>
</div>
<div id="chequeando-si-los-errores-tiene-varianza-constante" class="section level2 unnumbered hasAnchor">
<h2>Chequeando si los errores tiene varianza constante<a href="diag1.html#chequeando-si-los-errores-tiene-varianza-constante" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>En la siguiente figura se muestra el caso de varianza <span class="math inline">\(\sigma^2\)</span> constante (homocedasticidad) y el caso de varianza <span class="math inline">\(\sigma^2\)</span> no constante (heterocedasticidad). La homocedasticidad es el supuesto exigido en modelos de regresión.</p>
<p align="center">
<img src="images/homo_hetero.png" width="500">
</p>
<p>Para chequear si los errores tiene varianza constante se construye un gráfico de <span class="math inline">\(e_i\)</span> versus <span class="math inline">\(\hat{\mu}_i\)</span>, un gráfico similar al mostrado a continuación.</p>
<p align="center">
<img src="images/ei_versus_mui.png" width="450">
</p>
<p>En la siguiente figura se muestran los diferentes patrones que se pueden encontrar en el gráfico de <span class="math inline">\(e_i\)</span> versus <span class="math inline">\(\hat{\mu}_i\)</span>. Para que se cumpla el supuesto de homocedasticidad de los errores se necesita que los puntos se ubiquen como una nube de puntos sin ningún patrón claro. Cualquier patrón que se observe es evidencia de que no se cumple el supuesto de homocedasticidad de los errores.</p>
<p align="center">
<img src="images/patrones_ei_versus_mui.png" width="450">
</p>
<p>Una analogía útil para recordar si se cumple la homocedasticidad es que el gráfico de <span class="math inline">\(e_i\)</span> versus <span class="math inline">\(\hat{\mu}_i\)</span> tenga una apariencia como la mostrada en la siguiente figura.</p>
<p align="center">
<img src="images/cielo_estrellado.png" width="450">
</p>
<p>Otro gráfico útil para chequear el supuesto de homocedasticidad es dibujar un diagrama de dispersión de <span class="math inline">\(\sqrt{|d_i|}\)</span> versus <span class="math inline">\(\hat{\mu}_i\)</span>, un gráfico similar al mostrado a continuación.</p>
<p align="center">
<img src="images/di_versus_mui.png" width="450">
</p>
<p>Al igual que en el gráfico de <span class="math inline">\(e_i\)</span> versus <span class="math inline">\(\hat{\mu}_i\)</span>, se espera que no existan patrones claros en la nube de puntos.</p>
</div>
<div id="chequeando-si-errores-no-están-correlacionados" class="section level2 unnumbered hasAnchor">
<h2>Chequeando si errores no están correlacionados<a href="diag1.html#chequeando-si-errores-no-están-correlacionados" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Para estudiar esta situación se debe tener la historia de los errores, es decir, el orden en que las observaciones fueron tomadas. Usando es información se puede dibujar un diagrama de dispersión del residual versus tiempo, un gráfico similar al mostrado a continuación.</p>
<p align="center">
<img src="images/res_tiempo.png" width="450">
</p>
<p>En la siguiente figura se muestran los diferentes patrones que se pueden encontrar en el gráfico de <span class="math inline">\(e_i\)</span> versus el tiempo. Para que se cumpla el supuesto de independencia se espera que los puntos se ubiquen como una nube de puntos sin ningún patrón claro.</p>
<p align="center">
<img src="images/patrones_ei_tiempo.png" width="450">
</p>
<div id="ejemplo-cumpliendo-los-supuestos" class="section level3 unnumbered hasAnchor">
<h3>Ejemplo cumpliendo los supuestos<a href="diag1.html#ejemplo-cumpliendo-los-supuestos" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>En este ejemplo vamos a simular 500 observaciones del modelo mostrado abajo, luego vamos a ajustar un modelo correcto a los datos y por último vamos a realizar el análisis de residuales para saber si el modelo fue bien ajustado.</p>
<p><span class="math display">\[\begin{align*}
y_i &amp;\sim  N(\mu_i, \sigma^2) \\
\mu_i &amp;= 4 - 6 x_i \\
x_i &amp;\sim U(-5, 6) \\
\sigma^2 &amp;= 16
\end{align*}\]</span></p>
<p><strong>Solución</strong></p>
<p>Lo primero que se debe hacer es simular los datos y ajustar el modelo.</p>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="diag1.html#cb177-1" tabindex="-1"></a>gen_dat <span class="ot">&lt;-</span> <span class="cf">function</span>(n) {</span>
<span id="cb177-2"><a href="diag1.html#cb177-2" tabindex="-1"></a>  varianza <span class="ot">&lt;-</span> <span class="dv">16</span></span>
<span id="cb177-3"><a href="diag1.html#cb177-3" tabindex="-1"></a>  x <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="at">n=</span>n, <span class="at">min=</span><span class="sc">-</span><span class="dv">5</span>, <span class="at">max=</span><span class="dv">6</span>)</span>
<span id="cb177-4"><a href="diag1.html#cb177-4" tabindex="-1"></a>  media <span class="ot">&lt;-</span> <span class="dv">4</span> <span class="sc">-</span> <span class="dv">6</span> <span class="sc">*</span> x</span>
<span id="cb177-5"><a href="diag1.html#cb177-5" tabindex="-1"></a>  y <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n=</span>n, <span class="at">mean=</span>media, <span class="at">sd=</span><span class="fu">sqrt</span>(varianza))</span>
<span id="cb177-6"><a href="diag1.html#cb177-6" tabindex="-1"></a>  marco_datos <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">y=</span>y, <span class="at">x=</span>x)</span>
<span id="cb177-7"><a href="diag1.html#cb177-7" tabindex="-1"></a>  <span class="fu">return</span>(marco_datos)</span>
<span id="cb177-8"><a href="diag1.html#cb177-8" tabindex="-1"></a>}</span>
<span id="cb177-9"><a href="diag1.html#cb177-9" tabindex="-1"></a></span>
<span id="cb177-10"><a href="diag1.html#cb177-10" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">gen_dat</span>(<span class="at">n=</span><span class="dv">500</span>)</span>
<span id="cb177-11"><a href="diag1.html#cb177-11" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x, <span class="at">data=</span>datos)</span></code></pre></div>
<p>Los gráficos de residuales explicados anteriormente se pueden obtener usando la función <code>plot</code> sobre el modelo ajustado <code>mod</code>.</p>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="diag1.html#cb178-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb178-2"><a href="diag1.html#cb178-2" tabindex="-1"></a><span class="fu">plot</span>(mod, <span class="at">las=</span><span class="dv">1</span>, <span class="at">col=</span><span class="st">&#39;darkseagreen3&#39;</span>, <span class="at">which=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>)</span></code></pre></div>
<p><img src="Regresion_con_R_files/figure-html/resid01-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>En la figura anterior se observa que los puntos del gráfico de normalidad de los residuales estandarizados <span class="math inline">\(d_i\)</span> están muy cerca de la línea de referencia. Los diagramas de dispersión entre los residuales versus <span class="math inline">\(\hat{\mu}_i\)</span> no muestran ninguna anomalía. Por estas razones podemos asumir que los supuestos del modelo se cumplen.</p>
<p>Para estar más seguros de la normalidad de los errores vamos a aplicar la prueba <a href="https://en.wikipedia.org/wiki/Shapiro%E2%80%93Wilk_test">Shapiro-Wilks</a>. En esta prueba se tienen las siguiente hipótesis.</p>
<p><span class="math display">\[\begin{align}
H_0 &amp;: \text{los residuales tienen distribución normal.} \\
H_1 &amp;= \text{los residuales NO tienen distribución normal.}
\end{align}\]</span></p>
<p>Para aplicar la prueba podemos usar el siguiente código:</p>
<div class="sourceCode" id="cb179"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb179-1"><a href="diag1.html#cb179-1" tabindex="-1"></a>ei <span class="ot">&lt;-</span> <span class="fu">residuals</span>(mod)</span>
<span id="cb179-2"><a href="diag1.html#cb179-2" tabindex="-1"></a><span class="fu">shapiro.test</span>(ei)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  ei
## W = 0.99719, p-value = 0.5528</code></pre>
<p>De la salida anterior vemos que el valor-p es mayor que un nivel de significancia del 7 por ciento, eso significa que no hay evidencias para rechazar <span class="math inline">\(H_0\)</span>.</p>

<div class="rmdnote">
En este ejemplo se usó <code>plot(mod, which=1:3)</code> para obtener los tres primeros gráficos que entrega la función <code>plot</code>, el cuarto gráfico no es un gráfico de residuales y por eso se evitó en el ejemplo.
</div>
</div>
<div id="ejemplo-violando-los-supuestos" class="section level3 unnumbered hasAnchor">
<h3>Ejemplo violando los supuestos<a href="diag1.html#ejemplo-violando-los-supuestos" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>En este ejemplo vamos a simular 500 observaciones del modelo mostrado abajo en el cual modelo la media es función de <span class="math inline">\(x\)</span> y de <span class="math inline">\(x^2\)</span>. Luego vamos a ajustar un modelo <strong>incorrecto</strong> en el cual la media solo dependa de <span class="math inline">\(x\)</span> y por último vamos a construir los gráficos de residuales para ver si se logra identificar el problema.</p>
<p><span class="math display">\[\begin{align*}
y_i &amp;\sim  N(\mu_i, \sigma^2) \\
\mu_i &amp;= 4 - 6 x_i + 2 x_i^2 \\
x_i &amp;\sim U(-5, 6) \\
\sigma^2 &amp;= 16
\end{align*}\]</span></p>
<p><strong>Solución</strong></p>
<p>Lo primero que se debe hacer es simular los datos y ajustar el modelo.</p>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb181-1"><a href="diag1.html#cb181-1" tabindex="-1"></a>gen_dat <span class="ot">&lt;-</span> <span class="cf">function</span>(n) {</span>
<span id="cb181-2"><a href="diag1.html#cb181-2" tabindex="-1"></a>  varianza <span class="ot">&lt;-</span> <span class="dv">16</span></span>
<span id="cb181-3"><a href="diag1.html#cb181-3" tabindex="-1"></a>  x <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="at">n=</span>n, <span class="at">min=</span><span class="sc">-</span><span class="dv">5</span>, <span class="at">max=</span><span class="dv">6</span>)</span>
<span id="cb181-4"><a href="diag1.html#cb181-4" tabindex="-1"></a>  media <span class="ot">&lt;-</span> <span class="dv">4</span> <span class="sc">-</span> <span class="dv">6</span> <span class="sc">*</span> x <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> x<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb181-5"><a href="diag1.html#cb181-5" tabindex="-1"></a>  y <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n=</span>n, <span class="at">mean=</span>media, <span class="at">sd=</span><span class="fu">sqrt</span>(varianza))</span>
<span id="cb181-6"><a href="diag1.html#cb181-6" tabindex="-1"></a>  marco_datos <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">y=</span>y, <span class="at">x=</span>x)</span>
<span id="cb181-7"><a href="diag1.html#cb181-7" tabindex="-1"></a>  <span class="fu">return</span>(marco_datos)</span>
<span id="cb181-8"><a href="diag1.html#cb181-8" tabindex="-1"></a>}</span>
<span id="cb181-9"><a href="diag1.html#cb181-9" tabindex="-1"></a></span>
<span id="cb181-10"><a href="diag1.html#cb181-10" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">gen_dat</span>(<span class="at">n=</span><span class="dv">500</span>)</span>
<span id="cb181-11"><a href="diag1.html#cb181-11" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x, <span class="at">data=</span>datos)</span></code></pre></div>
<p>Los gráficos de residuales explicados anteriormente se pueden obtener usando la función <code>plot</code> sobre el modelo ajustado <code>mod</code>.</p>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb182-1"><a href="diag1.html#cb182-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb182-2"><a href="diag1.html#cb182-2" tabindex="-1"></a><span class="fu">plot</span>(mod, <span class="at">las=</span><span class="dv">1</span>, <span class="at">col=</span><span class="st">&#39;tomato&#39;</span>, <span class="at">which=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>)</span></code></pre></div>
<p><img src="Regresion_con_R_files/figure-html/resid02-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>De los gráficos anteriores se observa claramente que lo residuales no dicen que algo está mal con el modelo ajustado.</p>
<p>Para estar más seguros de la normalidad de los errores vamos a aplicar la prueba <a href="https://en.wikipedia.org/wiki/Shapiro%E2%80%93Wilk_test">Shapiro-Wilks</a>. En esta prueba se tienen las siguiente hipótesis.</p>
<p><span class="math display">\[\begin{align}
H_0 &amp;: \text{los residuales tienen distribución normal.} \\
H_1 &amp;= \text{los residuales NO tienen distribución normal.}
\end{align}\]</span></p>
<p>Para aplicar la prueba podemos usar el siguiente código:</p>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb183-1"><a href="diag1.html#cb183-1" tabindex="-1"></a>ei <span class="ot">&lt;-</span> <span class="fu">residuals</span>(mod)</span>
<span id="cb183-2"><a href="diag1.html#cb183-2" tabindex="-1"></a><span class="fu">shapiro.test</span>(ei)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  ei
## W = 0.93258, p-value = 3.105e-14</code></pre>
<p>De la salida anterior vemos que el valor-p es menor que un nivel de significancia del 7 por ciento, eso significa que no hay evidencias para rechazar <span class="math inline">\(H_0\)</span>.</p>
</div>
<div id="ejemplo-violando-los-supuestos-1" class="section level3 unnumbered hasAnchor">
<h3>Ejemplo violando los supuestos<a href="diag1.html#ejemplo-violando-los-supuestos-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>En este ejemplo vamos a simular 500 observaciones del modelo mostrado abajo en el cual la varianza de <span class="math inline">\(Y\)</span> es función de <span class="math inline">\(x\)</span>. Luego vamos a ajustar un modelo <strong>incorrecto</strong> en el cual asumimos que la varianza es constante y por último vamos a construir los gráficos de residuales para ver si se logra identificar el problema.</p>
<p><span class="math display">\[\begin{align*}
y_i &amp;\sim  N(\mu_i, \sigma^2) \\
\mu_i &amp;= 4 - 6 x_i \\
x_i &amp;\sim U(-5, 6) \\
\log(\sigma^2) &amp;= -1 + 0.5 x_i
\end{align*}\]</span></p>
<p><strong>Solución</strong></p>
<p>Lo primero que se debe hacer es simular los datos y ajustar el modelo.</p>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb185-1"><a href="diag1.html#cb185-1" tabindex="-1"></a>gen_dat <span class="ot">&lt;-</span> <span class="cf">function</span>(n) {</span>
<span id="cb185-2"><a href="diag1.html#cb185-2" tabindex="-1"></a>  x <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="at">n=</span>n, <span class="at">min=</span><span class="sc">-</span><span class="dv">5</span>, <span class="at">max=</span><span class="dv">6</span>)</span>
<span id="cb185-3"><a href="diag1.html#cb185-3" tabindex="-1"></a>  media <span class="ot">&lt;-</span> <span class="dv">4</span> <span class="sc">-</span> <span class="dv">6</span> <span class="sc">*</span> x</span>
<span id="cb185-4"><a href="diag1.html#cb185-4" tabindex="-1"></a>  varianza <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="sc">-</span><span class="dv">1</span> <span class="sc">+</span> <span class="fl">0.5</span> <span class="sc">*</span> x)</span>
<span id="cb185-5"><a href="diag1.html#cb185-5" tabindex="-1"></a>  y <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n=</span>n, <span class="at">mean=</span>media, <span class="at">sd=</span><span class="fu">sqrt</span>(varianza))</span>
<span id="cb185-6"><a href="diag1.html#cb185-6" tabindex="-1"></a>  marco_datos <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">y=</span>y, <span class="at">x=</span>x)</span>
<span id="cb185-7"><a href="diag1.html#cb185-7" tabindex="-1"></a>  <span class="fu">return</span>(marco_datos)</span>
<span id="cb185-8"><a href="diag1.html#cb185-8" tabindex="-1"></a>}</span>
<span id="cb185-9"><a href="diag1.html#cb185-9" tabindex="-1"></a></span>
<span id="cb185-10"><a href="diag1.html#cb185-10" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">gen_dat</span>(<span class="at">n=</span><span class="dv">500</span>)</span>
<span id="cb185-11"><a href="diag1.html#cb185-11" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x, <span class="at">data=</span>datos)</span></code></pre></div>
<p>Los gráficos de residuales explicados anteriormente se pueden obtener usando la función <code>plot</code> sobre el modelo ajustado <code>mod</code>.</p>
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb186-1"><a href="diag1.html#cb186-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb186-2"><a href="diag1.html#cb186-2" tabindex="-1"></a><span class="fu">plot</span>(mod, <span class="at">las=</span><span class="dv">1</span>, <span class="at">col=</span><span class="st">&#39;purple&#39;</span>, <span class="at">which=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>)</span></code></pre></div>
<p><img src="Regresion_con_R_files/figure-html/resid03-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>De los gráficos anteriores se observa claramente que lo residuales no dicen que algo está mal con el modelo ajustado.</p>
<p>Para estar más seguros de la normalidad de los errores vamos a aplicar la prueba <a href="https://en.wikipedia.org/wiki/Shapiro%E2%80%93Wilk_test">Shapiro-Wilks</a>. En esta prueba se tienen las siguiente hipótesis.</p>
<p><span class="math display">\[\begin{align}
H_0 &amp;: \text{los residuales tienen distribución normal.} \\
H_1 &amp;= \text{los residuales NO tienen distribución normal.}
\end{align}\]</span></p>
<p>Para aplicar la prueba podemos usar el siguiente código:</p>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb187-1"><a href="diag1.html#cb187-1" tabindex="-1"></a>ei <span class="ot">&lt;-</span> <span class="fu">residuals</span>(mod)</span>
<span id="cb187-2"><a href="diag1.html#cb187-2" tabindex="-1"></a><span class="fu">shapiro.test</span>(ei)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  ei
## W = 0.91551, p-value = 4.272e-16</code></pre>
<p>De la salida anterior vemos que el valor-p es menor que un nivel de significancia del 7 por ciento, eso significa que no hay evidencias para rechazar <span class="math inline">\(H_0\)</span>.</p>
</div>
</div>
<div id="gráficos-de-residuales-usando-car" class="section level2 unnumbered hasAnchor">
<h2>Gráficos de residuales usando car<a href="diag1.html#gráficos-de-residuales-usando-car" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>El paquete <strong>car</strong> de <span class="citation">John Fox, Weisberg, and Price (<a href="#ref-R-car">2023</a>)</span>, tiene unas funciones especiales para crear otro tipo de gráficos de residuales y que son útiles para identificar posibles anomalías en el modelo ajustado. A continuación las funciones para crear nuevos gráficos de residuales.</p>
<ul>
<li><code>residualPlots(model)</code>: dibuja una gráfica de los residuos de Pearson versus cada término del predictor lineal y los valores ajustados <span class="math inline">\(\hat{\mu}_i\)</span>. También entrega los resultados de una prueba de hipótesis para saber si se debe agregar un término cuadrático de cada variable.</li>
<li><code>mmps</code> o <code>marginalModelPlots(model)</code>: dibuja una gráfica de la respuesta <span class="math inline">\(y_i\)</span> versus cada covariable cuantitativa y los valores ajustados <span class="math inline">\(\hat{\mu}_i\)</span>, es una variación la propuesta de <span class="citation">Cook and Weisberg (<a href="#ref-cook_weisber97">1997</a>)</span>.</li>
</ul>
<div id="ejemplo-26" class="section level3 unnumbered hasAnchor">
<h3>Ejemplo<a href="diag1.html#ejemplo-26" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Este ejemplo corresponde al ejemplo mostrado en el capítulo 6 de <span class="citation">J. Fox and Weisberg (<a href="#ref-fox2019">2019</a>)</span>.</p>
<p>En este ejemplo se desea ajustar un modelo de regresión para explicar la media de la variable prestige en función de las variables education, income y type, usando la base de datos <code>Prestige</code> del paquete <strong>car</strong> <span class="citation">(<a href="#ref-R-car">John Fox, Weisberg, and Price 2023</a>)</span>.</p>
<p align="center">
<img src="images/canadian.jpg" width="250">
</p>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb189-1"><a href="diag1.html#cb189-1" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb189-2"><a href="diag1.html#cb189-2" tabindex="-1"></a>prestige_mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(prestige <span class="sc">~</span> education <span class="sc">+</span> income <span class="sc">+</span> type, <span class="at">data=</span>Prestige)</span></code></pre></div>
<p>Para construir los gráficos de los residuos de Pearson versus cada término del predictor lineal y los valores ajustados <span class="math inline">\(\hat{\mu}_i\)</span> se usa la siguiente instrucción (<code>las=1</code> para poner los números vertical en el eje Y).</p>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb190-1"><a href="diag1.html#cb190-1" tabindex="-1"></a><span class="fu">residualPlots</span>(prestige_mod1, <span class="at">las=</span><span class="dv">1</span>)</span></code></pre></div>
<p><img src="Regresion_con_R_files/figure-html/resid_car01-1.png" width="576" style="display: block; margin: auto;" /></p>
<pre><code>##            Test stat Pr(&gt;|Test stat|)   
## education    -0.6836         0.495942   
## income       -2.8865         0.004854 **
## type                                    
## Tukey test   -2.6104         0.009043 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>De la figura anterior se observa lo siguiente:</p>
<ul>
<li>El gráfico de residuales vs education se asemeja a un “gráfico nulo”, en la que ningún patrón particular es aparente.</li>
<li>El gráfico de residuales vs income presenta una curvatura.</li>
<li>El gráfico de residuales vs type (var. cuali.) presenta una apariencia de un “gráfico nulo”, todas las cajas con a proximadamente el mismo centro y extensión.</li>
<li>De los tres comentarios anteriores parece que falta el término <span class="math inline">\(Income^2\)</span> en el predictor lineal.</li>
</ul>
<p>La sospecha de que falta el término <span class="math inline">\(Income^2\)</span> se ve reforzada por la tabla que acompaña la salida de <code>residualPlots(prestige_mod)</code>. En la línea para la variable <code>income</code> se tiene la prueba de hipótesis:</p>
<ul>
<li><span class="math inline">\(H_0:\)</span> no se necesita <span class="math inline">\(Income^2\)</span>,</li>
<li><span class="math inline">\(H_A:\)</span> si se necesita <span class="math inline">\(Income^2\)</span>.</li>
</ul>
<p>El valor-P de esta prueba es 0.004854 y por lo tanto se justifica incluir <span class="math inline">\(Income^2\)</span>.</p>
<p>Para dibujar los gráficos marginales de <span class="math inline">\(y_i\)</span> versus cada covariable cuantitativa y los valores ajustados <span class="math inline">\(\hat{\mu}_i\)</span> se usa la siguiente instrucción.</p>
<div class="sourceCode" id="cb192"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb192-1"><a href="diag1.html#cb192-1" tabindex="-1"></a><span class="fu">marginalModelPlots</span>(prestige_mod1, <span class="at">las=</span><span class="dv">1</span>)</span></code></pre></div>
<pre><code>## Warning in mmps(...): Interactions and/or factors skipped</code></pre>
<p><img src="Regresion_con_R_files/figure-html/resid_car02-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>La línea de color azul es una regresión lowess entre <span class="math inline">\(y_i\)</span> y la variable que está en el eje horizontal. La línea de color rojo es una regresión lowess entre <span class="math inline">\(\hat{\mu}_i\)</span> y la variable que está en el eje horizontal. Según <span class="citation">J. Fox and Weisberg (<a href="#ref-fox2019">2019</a>)</span>, si el modelo se ajusta bien a los datos, las líneas (azul y roja) estarán próximas, por el contrario, si las líneas difieren demasiado, es evidencia de que el modelo no explica bien los datos.</p>
<p>De la figura anterior se observa que las líneas (azul y roja) difieren un poco en el panel de <span class="math inline">\(y_i\)</span> versus income, eso refuerza lo observado antes de que sería bueno agregar un término <code>I(income^2)</code>.</p>
<div class="sourceCode" id="cb194"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb194-1"><a href="diag1.html#cb194-1" tabindex="-1"></a>prestige_mod2 <span class="ot">&lt;-</span> <span class="fu">lm</span> (prestige <span class="sc">~</span> education <span class="sc">+</span> income <span class="sc">+</span> <span class="fu">I</span>(income<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> type, <span class="at">data=</span>Prestige)</span></code></pre></div>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb195-1"><a href="diag1.html#cb195-1" tabindex="-1"></a><span class="fu">residualPlots</span>(prestige_mod2, <span class="at">las=</span><span class="dv">1</span>)</span></code></pre></div>
<p><img src="Regresion_con_R_files/figure-html/resid_car03-1.png" width="576" style="display: block; margin: auto;" /></p>
<pre><code>##             Test stat Pr(&gt;|Test stat|)  
## education     -0.3844          0.70156  
## income         0.4760          0.63520  
## I(income^2)    2.1493          0.03426 *
## type                                    
## Tukey test    -2.1877          0.02869 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb197-1"><a href="diag1.html#cb197-1" tabindex="-1"></a><span class="fu">anova</span>(prestige_mod1, prestige_mod2)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: prestige ~ education + income + type
## Model 2: prestige ~ education + income + I(income^2) + type
##   Res.Df    RSS Df Sum of Sq      F   Pr(&gt;F)   
## 1     93 4681.3                                
## 2     92 4292.5  1    388.74 8.3317 0.004854 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
</div>
<div id="prueba-de-falta-de-ajuste" class="section level2 unnumbered hasAnchor">
<h2>Prueba de falta de ajuste<a href="diag1.html#prueba-de-falta-de-ajuste" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Para el caso de la RLS, se quiere probar:</p>
<p><span class="math display">\[
\begin{aligned}
\begin{cases}
H_0:\ E(Y_i) = E(Y\vert X_i) = \beta_0 + \beta_1 X_i\\ \\
H_1:\ E(Y_i) = E(Y\vert X_i) \neq \beta_0 + \beta_1 X_i
\end{cases}
\end{aligned}
\]</span></p>
<p>Para aplicar esta prueba construye la tabla anova de la siguiente manera:</p>
<p>Bajo la hipótesis nula <span class="math inline">\({H_0:\ E(Y_i) = \beta_0 + \beta_1x_i}\)</span>, el estadístico se distribuye como una <span class="math inline">\(F\)</span> con <span class="math inline">\((m - 2)\)</span> y <span class="math inline">\((n - m)\)</span> grados de libertad. Así, a un nivel de significancia <span class="math inline">\({\alpha}\)</span> <strong>se rechaza la hipótesis nula de que el modelo lineal es adecuado</strong> (en favor de la hipótesis de que el modelo lineal tiene falta de ajuste) si <span class="math inline">\({F_0 &gt; F_{\alpha, m - 2, n - m}}\)</span>.</p>
<div id="ejemplo-1-1" class="section level3 unnumbered hasAnchor">
<h3>Ejemplo 1<a href="diag1.html#ejemplo-1-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Suponga que se tienen los siguientes datos.</p>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb199-1"><a href="diag1.html#cb199-1" tabindex="-1"></a><span class="co"># Example for section 4.5 Montgomery, Peck &amp; Vining (2006)</span></span>
<span id="cb199-2"><a href="diag1.html#cb199-2" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">1.0</span>, <span class="fl">1.0</span>, <span class="fl">2.0</span>, <span class="fl">3.3</span>, <span class="fl">3.3</span>, <span class="fl">4.0</span>, <span class="fl">4.0</span>, <span class="fl">4.0</span>, <span class="fl">4.7</span>, <span class="fl">5.0</span>,</span>
<span id="cb199-3"><a href="diag1.html#cb199-3" tabindex="-1"></a>       <span class="fl">5.6</span>, <span class="fl">5.6</span>, <span class="fl">5.6</span>, <span class="fl">6.0</span>, <span class="fl">6.0</span>, <span class="fl">6.5</span>, <span class="fl">6.9</span>)</span>
<span id="cb199-4"><a href="diag1.html#cb199-4" tabindex="-1"></a></span>
<span id="cb199-5"><a href="diag1.html#cb199-5" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">10.84</span>, <span class="fl">9.30</span>, <span class="fl">16.35</span>, <span class="fl">22.88</span>, <span class="fl">24.35</span>, <span class="fl">24.56</span>, <span class="fl">25.86</span>,</span>
<span id="cb199-6"><a href="diag1.html#cb199-6" tabindex="-1"></a>       <span class="fl">29.16</span>, <span class="fl">24.59</span>, <span class="fl">22.25</span>, <span class="fl">25.90</span>, <span class="fl">27.20</span>, <span class="fl">25.61</span>, <span class="fl">25.45</span>,</span>
<span id="cb199-7"><a href="diag1.html#cb199-7" tabindex="-1"></a>       <span class="fl">26.56</span>, <span class="fl">21.03</span>, <span class="fl">21.46</span>)</span></code></pre></div>
<p>¿Es el modelo de regresión lineal simple apropiado para explicar <span class="math inline">\(Y\)</span> en función de <span class="math inline">\(X\)</span>?</p>
<p><strong>Solución</strong></p>
<p>Primero exploremos la relación entre las variables.</p>
<div class="sourceCode" id="cb200"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb200-1"><a href="diag1.html#cb200-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x=</span>x, <span class="at">y=</span>y, <span class="at">pch=</span><span class="dv">20</span>, <span class="at">cex=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="Regresion_con_R_files/figure-html/lof01-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>Luego vamos a ajustar el modelo.</p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb201-1"><a href="diag1.html#cb201-1" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x)</span></code></pre></div>
<p>Luego construimos la tabla anova por medio de la función <code>lack_fit_test</code> del paquete <strong>model</strong>. Para instalar el paquete <strong>model</strong> podemos usar el siguiente código.</p>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb202-1"><a href="diag1.html#cb202-1" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(<span class="st">&quot;remotes&quot;</span>)) <span class="fu">install.packages</span>(<span class="st">&quot;remotes&quot;</span>)</span>
<span id="cb202-2"><a href="diag1.html#cb202-2" tabindex="-1"></a>remotes<span class="sc">::</span><span class="fu">install_github</span>(<span class="st">&quot;fhernanb/model&quot;</span>)</span></code></pre></div>
<p>Luego de esto ya podemos usar la función <code>lack_fit_test</code>.</p>
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb203-1"><a href="diag1.html#cb203-1" tabindex="-1"></a><span class="fu">library</span>(model)</span>
<span id="cb203-2"><a href="diag1.html#cb203-2" tabindex="-1"></a><span class="fu">lack_fit_test</span>(mod)</span></code></pre></div>
<pre><code>## Lack of fit test - Anova Table
##             Sum Sq Df Mean Sq F value   Pr(&gt;F)   
## Regression  237.48  1 237.479  14.241 0.001839 **
## Residuals   250.13 15  16.676                    
## Lack of fit 234.57  8  29.321  13.188 0.001389 **
## Pure error   15.56  7   2.223                    
## Total       487.61 16                            
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>De la salida anterior tenemos un valor-P de 0.001389 con lo cual podemos decir que hay evidencias para rechazar <span class="math inline">\(H_0\)</span>.</p>
<div class="sourceCode" id="cb205"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb205-1"><a href="diag1.html#cb205-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x=</span>x, <span class="at">y=</span>y, <span class="at">pch=</span><span class="dv">20</span>, <span class="at">cex=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span>
<span id="cb205-2"><a href="diag1.html#cb205-2" tabindex="-1"></a><span class="fu">abline</span>(mod, <span class="at">lty=</span><span class="st">&quot;dashed&quot;</span>, <span class="at">col=</span><span class="st">&quot;blue&quot;</span>, <span class="at">lwd=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="Regresion_con_R_files/figure-html/lof02-1.png" width="576" style="display: block; margin: auto;" /></p>
</div>
<div id="ejemplo-2-1" class="section level3 unnumbered hasAnchor">
<h3>Ejemplo 2<a href="diag1.html#ejemplo-2-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Suponga que se tienen los siguientes datos.</p>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb206-1"><a href="diag1.html#cb206-1" tabindex="-1"></a><span class="co"># Example 9.6 Montgomery &amp; Runger (1996)</span></span>
<span id="cb206-2"><a href="diag1.html#cb206-2" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">1.0</span>, <span class="fl">1.0</span>, <span class="fl">2.0</span>, <span class="fl">3.3</span>, <span class="fl">3.3</span>, <span class="fl">4.0</span>, <span class="fl">4.0</span>, <span class="fl">4.0</span>, <span class="fl">5.0</span>,</span>
<span id="cb206-3"><a href="diag1.html#cb206-3" tabindex="-1"></a>       <span class="fl">5.6</span>, <span class="fl">5.6</span>, <span class="fl">5.6</span>, <span class="fl">6.0</span>, <span class="fl">6.0</span>, <span class="fl">6.5</span>, <span class="fl">6.9</span>)</span>
<span id="cb206-4"><a href="diag1.html#cb206-4" tabindex="-1"></a></span>
<span id="cb206-5"><a href="diag1.html#cb206-5" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">2.3</span>, <span class="fl">1.8</span>, <span class="fl">2.8</span>, <span class="fl">1.8</span>, <span class="fl">3.7</span>, <span class="fl">2.6</span>, <span class="fl">2.6</span>, <span class="fl">2.2</span>, <span class="fl">2.0</span>, <span class="fl">3.5</span>,</span>
<span id="cb206-6"><a href="diag1.html#cb206-6" tabindex="-1"></a>       <span class="fl">2.8</span>, <span class="fl">2.1</span>, <span class="fl">3.4</span>, <span class="fl">3.2</span>, <span class="fl">3.4</span>, <span class="fl">5.0</span>)</span></code></pre></div>
<p>¿Es el modelo de regresión lineal simple apropiado para explicar <span class="math inline">\(Y\)</span> en función de <span class="math inline">\(X\)</span>?</p>
<p><strong>Solución</strong></p>
<p>Primero exploremos la relación entre las variables.</p>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb207-1"><a href="diag1.html#cb207-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x=</span>x, <span class="at">y=</span>y, <span class="at">pch=</span><span class="dv">20</span>, <span class="at">cex=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">&quot;chartreuse3&quot;</span>)</span></code></pre></div>
<p><img src="Regresion_con_R_files/figure-html/lof03-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>Luego vamos a ajustar el modelo.</p>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb208-1"><a href="diag1.html#cb208-1" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x)</span></code></pre></div>
<p>Luego construimos la tabla anova por medio de la función <code>lack_fit_test</code> del paquete <strong>model</strong>. Para instalar el paquete <strong>model</strong> podemos usar el siguiente código.</p>
<div class="sourceCode" id="cb209"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb209-1"><a href="diag1.html#cb209-1" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(<span class="st">&quot;remotes&quot;</span>)) <span class="fu">install.packages</span>(<span class="st">&quot;remotes&quot;</span>)</span>
<span id="cb209-2"><a href="diag1.html#cb209-2" tabindex="-1"></a>remotes<span class="sc">::</span><span class="fu">install_github</span>(<span class="st">&quot;fhernanb/model&quot;</span>)</span></code></pre></div>
<p>Luego de esto ya podemos usar la función <code>lack_fit_test</code>.</p>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb210-1"><a href="diag1.html#cb210-1" tabindex="-1"></a><span class="fu">library</span>(model)</span>
<span id="cb210-2"><a href="diag1.html#cb210-2" tabindex="-1"></a><span class="fu">lack_fit_test</span>(mod)</span></code></pre></div>
<pre><code>## Lack of fit test - Anova Table
##              Sum Sq Df Mean Sq F value  Pr(&gt;F)  
## Regression   3.4928  1  3.4928  6.6645 0.02174 *
## Residuals    7.3372 14  0.5241                  
## Lack of fit  4.3005  7  0.6144  1.4162 0.32882  
## Pure error   3.0367  7  0.4338                  
## Total       10.8300 15                          
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>De la salida anterior tenemos un valor-P de 0.32882 con lo cual podemos decir que NO hay evidencias para rechazar <span class="math inline">\(H_0\)</span>.</p>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb212-1"><a href="diag1.html#cb212-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x=</span>x, <span class="at">y=</span>y, <span class="at">pch=</span><span class="dv">20</span>, <span class="at">cex=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">&quot;chartreuse3&quot;</span>)</span>
<span id="cb212-2"><a href="diag1.html#cb212-2" tabindex="-1"></a><span class="fu">abline</span>(mod, <span class="at">lty=</span><span class="st">&quot;dashed&quot;</span>, <span class="at">col=</span><span class="st">&quot;mediumpurple2&quot;</span>, <span class="at">lwd=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="Regresion_con_R_files/figure-html/lof04-1.png" width="576" style="display: block; margin: auto;" /></p>

</div>
</div>
</div>
<h3>References<a href="references.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-cook_weisber97" class="csl-entry">
Cook, R. Dennis, and Sanford Weisberg. 1997. <span>“Graphics for Assessing the Adequacy of Regression Models.”</span> <em>Journal of the American Statistical Association</em> 92 (438): 490–99. <a href="https://doi.org/10.1080/01621459.1997.10474002">https://doi.org/10.1080/01621459.1997.10474002</a>.
</div>
<div id="ref-R-car" class="csl-entry">
Fox, John, Sanford Weisberg, and Brad Price. 2023. <em>Car: Companion to Applied Regression</em>. <a href="https://r-forge.r-project.org/projects/car/">https://r-forge.r-project.org/projects/car/</a>.
</div>
<div id="ref-fox2019" class="csl-entry">
Fox, J., and W. Weisberg. 2019. <em>An r Companion to Applied Regression</em>. Third. SAGE Publications, Inc.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="ph2.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="diag2.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/fhernanb/libro_regresion/edit/master/09-diag1.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
